// Autogenerated with StateSmith 0.19.0+b5719011215d41a81572ed347c02b22db5d1a48f.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

// Whatever you put in this `FileTop` section will end up 
// being printed at the top of every generated code file.

#include "tracingStateMachine.hpp"
#include <stdbool.h> // required for `consume_event` flag
#include <string.h> // for memset
    

// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(tracingStateMachine* sm, tracingStateMachine_StateId desired_state);

static void ROOT_enter(tracingStateMachine* sm);

static void ABORTSTATE_enter(tracingStateMachine* sm);

static void ABORTSTATE_exit(tracingStateMachine* sm);

static void ABORTSTATE_do(tracingStateMachine* sm);

static void ALLPLANNED_enter(tracingStateMachine* sm);

static void ALLPLANNED_exit(tracingStateMachine* sm);

static void ALLPLANNED_do(tracingStateMachine* sm);

static void ATTEMPTNEXTCLOSESTSTATE_enter(tracingStateMachine* sm);

static void ATTEMPTNEXTCLOSESTSTATE_exit(tracingStateMachine* sm);

static void ATTEMPTNEXTCLOSESTSTATE_do(tracingStateMachine* sm);

static void INITSTATE_enter(tracingStateMachine* sm);

static void INITSTATE_exit(tracingStateMachine* sm);

static void INITSTATE_do(tracingStateMachine* sm);

static void JUMPTOBRANCHSTATE_enter(tracingStateMachine* sm);

static void JUMPTOBRANCHSTATE_exit(tracingStateMachine* sm);

static void jumpToBranchState_ChoicePoint__transition(tracingStateMachine* sm);

static void CHECKSIZESTATE_enter(tracingStateMachine* sm);

static void CHECKSIZESTATE_exit(tracingStateMachine* sm);

static void CHECKSIZESTATE_do(tracingStateMachine* sm);

static void FAILEDJUMPSTATE_enter(tracingStateMachine* sm);

static void FAILEDJUMPSTATE_exit(tracingStateMachine* sm);

static void FAILEDJUMPSTATE_do(tracingStateMachine* sm);

static void GETCANDIDATESSTATE_enter(tracingStateMachine* sm);

static void GETCANDIDATESSTATE_exit(tracingStateMachine* sm);

static void GETCANDIDATESSTATE_do(tracingStateMachine* sm);

static void JUMPTOTRIANGLESTATE_enter(tracingStateMachine* sm);

static void JUMPTOTRIANGLESTATE_exit(tracingStateMachine* sm);

static void FAIL_enter(tracingStateMachine* sm);

static void FAIL_exit(tracingStateMachine* sm);

static void FAIL_do(tracingStateMachine* sm);

static void FALLBACKPREPSTATE_enter(tracingStateMachine* sm);

static void FALLBACKPREPSTATE_exit(tracingStateMachine* sm);

static void FALLBACKPREPSTATE_do(tracingStateMachine* sm);

static void LIFTEDPOSERANDOMTRAJSTATE_enter(tracingStateMachine* sm);

static void LIFTEDPOSERANDOMTRAJSTATE_exit(tracingStateMachine* sm);

static void LIFTEDPOSERANDOMTRAJSTATE_do(tracingStateMachine* sm);

static void LIFTEDPOSESTARIGHTLINESTATE_enter(tracingStateMachine* sm);

static void LIFTEDPOSESTARIGHTLINESTATE_exit(tracingStateMachine* sm);

static void LIFTEDPOSESTARIGHTLINESTATE_do(tracingStateMachine* sm);

static void MOVEWITHLIFTSTATE_enter(tracingStateMachine* sm);

static void MOVEWITHLIFTSTATE_exit(tracingStateMachine* sm);

static void MOVEWITHLIFTSTATE_do(tracingStateMachine* sm);

static void TARGETPOSESTRAIGHTLINESTATE_enter(tracingStateMachine* sm);

static void TARGETPOSESTRAIGHTLINESTATE_exit(tracingStateMachine* sm);

static void TARGETPOSESTRAIGHTLINESTATE_do(tracingStateMachine* sm);

static void TRIANGSETUPSTATE_enter(tracingStateMachine* sm);

static void TRIANGSETUPSTATE_exit(tracingStateMachine* sm);

static void TRIANGSETUPSTATE_do(tracingStateMachine* sm);

static void SUCCESSFULJUMPSTATE_enter(tracingStateMachine* sm);

static void SUCCESSFULJUMPSTATE_exit(tracingStateMachine* sm);

static void SUCCESSFULJUMPSTATE_do(tracingStateMachine* sm);

static void LEASTNEIGHBOURSSEARCHSTATE_enter(tracingStateMachine* sm);

static void LEASTNEIGHBOURSSEARCHSTATE_exit(tracingStateMachine* sm);

static void LEASTNEIGHBOURSSEARCHSTATE_do(tracingStateMachine* sm);

static void REACHINGSTATE_enter(tracingStateMachine* sm);

static void REACHINGSTATE_exit(tracingStateMachine* sm);

static void GETCLOSESTSTATE_enter(tracingStateMachine* sm);

static void GETCLOSESTSTATE_exit(tracingStateMachine* sm);

static void GETCLOSESTSTATE_do(tracingStateMachine* sm);

static void GETPOSESTATEINREACHING_enter(tracingStateMachine* sm);

static void GETPOSESTATEINREACHING_exit(tracingStateMachine* sm);

static void GETPOSESTATEINREACHING_do(tracingStateMachine* sm);

static void MOVESTATEINREACHING_enter(tracingStateMachine* sm);

static void MOVESTATEINREACHING_exit(tracingStateMachine* sm);

static void MOVESTATEINREACHING_do(tracingStateMachine* sm);

static void REACHFAILED_enter(tracingStateMachine* sm);

static void REACHFAILED_exit(tracingStateMachine* sm);

static void REACHFAILED_do(tracingStateMachine* sm);

static void TRACENEIGHBOURSTATE_enter(tracingStateMachine* sm);

static void TRACENEIGHBOURSTATE_exit(tracingStateMachine* sm);

static void FINISHTRANSBETWEENTRIANGLESSTATE_enter(tracingStateMachine* sm);

static void FINISHTRANSBETWEENTRIANGLESSTATE_exit(tracingStateMachine* sm);

static void FINISHTRANSBETWEENTRIANGLESSTATE_do(tracingStateMachine* sm);

static void MOVEFROMEDGESTATE_enter(tracingStateMachine* sm);

static void MOVEFROMEDGESTATE_exit(tracingStateMachine* sm);

static void MOVEFROMEDGESTATE_do(tracingStateMachine* sm);

static void MOVETOEDGESTATE_enter(tracingStateMachine* sm);

static void MOVETOEDGESTATE_exit(tracingStateMachine* sm);

static void MOVETOEDGESTATE_do(tracingStateMachine* sm);

static void POPHISTRORYANDMOVEBACKSTATE_enter(tracingStateMachine* sm);

static void POPHISTRORYANDMOVEBACKSTATE_exit(tracingStateMachine* sm);

static void POPHISTRORYANDMOVEBACKSTATE_do(tracingStateMachine* sm);

static void ROTATEAROUNDEDGESTATE_enter(tracingStateMachine* sm);

static void ROTATEAROUNDEDGESTATE_exit(tracingStateMachine* sm);

static void ROTATEAROUNDEDGESTATE_do(tracingStateMachine* sm);

static void UPDVALSONFAILSTATE_enter(tracingStateMachine* sm);

static void UPDVALSONFAILSTATE_exit(tracingStateMachine* sm);

static void UPDVALSONFAILSTATE_do(tracingStateMachine* sm);


// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void tracingStateMachine_ctor(tracingStateMachine* sm)
{
    memset(sm, 0, sizeof(*sm));
}

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void tracingStateMachine_start(tracingStateMachine* sm)
{
    ROOT_enter(sm);
    // ROOT behavior
    // uml: TransitionTo(ROOT.<InitialState>)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
        // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.
        
        // ROOT.<InitialState> behavior
        // uml: TransitionTo(initState)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `initState`.
            INITSTATE_enter(sm);
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for ROOT.<InitialState>
    } // end of behavior for ROOT
}

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void tracingStateMachine_dispatch_event(tracingStateMachine* sm, tracingStateMachine_EventId event_id)
{
    // This state machine design only has a single event type so we can safely assume
    // that the dispatched event is `do` without checking the `event_id` parameter.
    (void)event_id; // This line prevents an 'unused variable' compiler warning
    
    switch (sm->state_id)
    {
        // STATE: tracingStateMachine
        case tracingStateMachine_StateId_ROOT:
            // state and ancestors have no handler for `do` event.
            break;
        
        // STATE: abortState
        case tracingStateMachine_StateId_ABORTSTATE:
            ABORTSTATE_do(sm); 
            break;
        
        // STATE: allPlanned
        case tracingStateMachine_StateId_ALLPLANNED:
            ALLPLANNED_do(sm); 
            break;
        
        // STATE: attemptNextClosestState
        case tracingStateMachine_StateId_ATTEMPTNEXTCLOSESTSTATE:
            ATTEMPTNEXTCLOSESTSTATE_do(sm); 
            break;
        
        // STATE: initState
        case tracingStateMachine_StateId_INITSTATE:
            INITSTATE_do(sm); 
            break;
        
        // STATE: jumpToBranchState
        case tracingStateMachine_StateId_JUMPTOBRANCHSTATE:
            // state and ancestors have no handler for `do` event.
            break;
        
        // STATE: checkSizeState
        case tracingStateMachine_StateId_CHECKSIZESTATE:
            CHECKSIZESTATE_do(sm); 
            break;
        
        // STATE: failedJumpState
        case tracingStateMachine_StateId_FAILEDJUMPSTATE:
            FAILEDJUMPSTATE_do(sm); 
            break;
        
        // STATE: getCandidatesState
        case tracingStateMachine_StateId_GETCANDIDATESSTATE:
            GETCANDIDATESSTATE_do(sm); 
            break;
        
        // STATE: jumpToTriangleState
        case tracingStateMachine_StateId_JUMPTOTRIANGLESTATE:
            // state and ancestors have no handler for `do` event.
            break;
        
        // STATE: fail
        case tracingStateMachine_StateId_FAIL:
            FAIL_do(sm); 
            break;
        
        // STATE: fallbackPrepState
        case tracingStateMachine_StateId_FALLBACKPREPSTATE:
            FALLBACKPREPSTATE_do(sm); 
            break;
        
        // STATE: liftedPoseRandomTrajState
        case tracingStateMachine_StateId_LIFTEDPOSERANDOMTRAJSTATE:
            LIFTEDPOSERANDOMTRAJSTATE_do(sm); 
            break;
        
        // STATE: liftedPoseStarightLineState
        case tracingStateMachine_StateId_LIFTEDPOSESTARIGHTLINESTATE:
            LIFTEDPOSESTARIGHTLINESTATE_do(sm); 
            break;
        
        // STATE: moveWithLiftState
        case tracingStateMachine_StateId_MOVEWITHLIFTSTATE:
            MOVEWITHLIFTSTATE_do(sm); 
            break;
        
        // STATE: targetPoseStraightLineState
        case tracingStateMachine_StateId_TARGETPOSESTRAIGHTLINESTATE:
            TARGETPOSESTRAIGHTLINESTATE_do(sm); 
            break;
        
        // STATE: triangSetupState
        case tracingStateMachine_StateId_TRIANGSETUPSTATE:
            TRIANGSETUPSTATE_do(sm); 
            break;
        
        // STATE: successfulJumpState
        case tracingStateMachine_StateId_SUCCESSFULJUMPSTATE:
            SUCCESSFULJUMPSTATE_do(sm); 
            break;
        
        // STATE: leastNeighboursSearchState
        case tracingStateMachine_StateId_LEASTNEIGHBOURSSEARCHSTATE:
            LEASTNEIGHBOURSSEARCHSTATE_do(sm); 
            break;
        
        // STATE: reachingState
        case tracingStateMachine_StateId_REACHINGSTATE:
            // state and ancestors have no handler for `do` event.
            break;
        
        // STATE: getClosestState
        case tracingStateMachine_StateId_GETCLOSESTSTATE:
            GETCLOSESTSTATE_do(sm); 
            break;
        
        // STATE: getPoseStateInReaching
        case tracingStateMachine_StateId_GETPOSESTATEINREACHING:
            GETPOSESTATEINREACHING_do(sm); 
            break;
        
        // STATE: moveStateInReaching
        case tracingStateMachine_StateId_MOVESTATEINREACHING:
            MOVESTATEINREACHING_do(sm); 
            break;
        
        // STATE: reachFailed
        case tracingStateMachine_StateId_REACHFAILED:
            REACHFAILED_do(sm); 
            break;
        
        // STATE: traceNeighbourState
        case tracingStateMachine_StateId_TRACENEIGHBOURSTATE:
            // state and ancestors have no handler for `do` event.
            break;
        
        // STATE: finishTransBetweenTrianglesState
        case tracingStateMachine_StateId_FINISHTRANSBETWEENTRIANGLESSTATE:
            FINISHTRANSBETWEENTRIANGLESSTATE_do(sm); 
            break;
        
        // STATE: moveFromEdgeState
        case tracingStateMachine_StateId_MOVEFROMEDGESTATE:
            MOVEFROMEDGESTATE_do(sm); 
            break;
        
        // STATE: moveToEdgeState
        case tracingStateMachine_StateId_MOVETOEDGESTATE:
            MOVETOEDGESTATE_do(sm); 
            break;
        
        // STATE: popHistroryAndMoveBackState
        case tracingStateMachine_StateId_POPHISTRORYANDMOVEBACKSTATE:
            POPHISTRORYANDMOVEBACKSTATE_do(sm); 
            break;
        
        // STATE: rotateAroundEdgeState
        case tracingStateMachine_StateId_ROTATEAROUNDEDGESTATE:
            ROTATEAROUNDEDGESTATE_do(sm); 
            break;
        
        // STATE: updValsOnFailState
        case tracingStateMachine_StateId_UPDVALSONFAILSTATE:
            UPDVALSONFAILSTATE_do(sm); 
            break;
    }
    
}

// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(tracingStateMachine* sm, tracingStateMachine_StateId desired_state)
{
    while (sm->state_id != desired_state)
    {
        switch (sm->state_id)
        {
            case tracingStateMachine_StateId_ABORTSTATE: ABORTSTATE_exit(sm); break;
            
            case tracingStateMachine_StateId_ALLPLANNED: ALLPLANNED_exit(sm); break;
            
            case tracingStateMachine_StateId_ATTEMPTNEXTCLOSESTSTATE: ATTEMPTNEXTCLOSESTSTATE_exit(sm); break;
            
            case tracingStateMachine_StateId_INITSTATE: INITSTATE_exit(sm); break;
            
            case tracingStateMachine_StateId_JUMPTOBRANCHSTATE: JUMPTOBRANCHSTATE_exit(sm); break;
            
            case tracingStateMachine_StateId_CHECKSIZESTATE: CHECKSIZESTATE_exit(sm); break;
            
            case tracingStateMachine_StateId_FAILEDJUMPSTATE: FAILEDJUMPSTATE_exit(sm); break;
            
            case tracingStateMachine_StateId_GETCANDIDATESSTATE: GETCANDIDATESSTATE_exit(sm); break;
            
            case tracingStateMachine_StateId_JUMPTOTRIANGLESTATE: JUMPTOTRIANGLESTATE_exit(sm); break;
            
            case tracingStateMachine_StateId_FAIL: FAIL_exit(sm); break;
            
            case tracingStateMachine_StateId_FALLBACKPREPSTATE: FALLBACKPREPSTATE_exit(sm); break;
            
            case tracingStateMachine_StateId_LIFTEDPOSERANDOMTRAJSTATE: LIFTEDPOSERANDOMTRAJSTATE_exit(sm); break;
            
            case tracingStateMachine_StateId_LIFTEDPOSESTARIGHTLINESTATE: LIFTEDPOSESTARIGHTLINESTATE_exit(sm); break;
            
            case tracingStateMachine_StateId_MOVEWITHLIFTSTATE: MOVEWITHLIFTSTATE_exit(sm); break;
            
            case tracingStateMachine_StateId_TARGETPOSESTRAIGHTLINESTATE: TARGETPOSESTRAIGHTLINESTATE_exit(sm); break;
            
            case tracingStateMachine_StateId_TRIANGSETUPSTATE: TRIANGSETUPSTATE_exit(sm); break;
            
            case tracingStateMachine_StateId_SUCCESSFULJUMPSTATE: SUCCESSFULJUMPSTATE_exit(sm); break;
            
            case tracingStateMachine_StateId_LEASTNEIGHBOURSSEARCHSTATE: LEASTNEIGHBOURSSEARCHSTATE_exit(sm); break;
            
            case tracingStateMachine_StateId_REACHINGSTATE: REACHINGSTATE_exit(sm); break;
            
            case tracingStateMachine_StateId_GETCLOSESTSTATE: GETCLOSESTSTATE_exit(sm); break;
            
            case tracingStateMachine_StateId_GETPOSESTATEINREACHING: GETPOSESTATEINREACHING_exit(sm); break;
            
            case tracingStateMachine_StateId_MOVESTATEINREACHING: MOVESTATEINREACHING_exit(sm); break;
            
            case tracingStateMachine_StateId_REACHFAILED: REACHFAILED_exit(sm); break;
            
            case tracingStateMachine_StateId_TRACENEIGHBOURSTATE: TRACENEIGHBOURSTATE_exit(sm); break;
            
            case tracingStateMachine_StateId_FINISHTRANSBETWEENTRIANGLESSTATE: FINISHTRANSBETWEENTRIANGLESSTATE_exit(sm); break;
            
            case tracingStateMachine_StateId_MOVEFROMEDGESTATE: MOVEFROMEDGESTATE_exit(sm); break;
            
            case tracingStateMachine_StateId_MOVETOEDGESTATE: MOVETOEDGESTATE_exit(sm); break;
            
            case tracingStateMachine_StateId_POPHISTRORYANDMOVEBACKSTATE: POPHISTRORYANDMOVEBACKSTATE_exit(sm); break;
            
            case tracingStateMachine_StateId_ROTATEAROUNDEDGESTATE: ROTATEAROUNDEDGESTATE_exit(sm); break;
            
            case tracingStateMachine_StateId_UPDVALSONFAILSTATE: UPDVALSONFAILSTATE_exit(sm); break;
            
            default: return;  // Just to be safe. Prevents infinite loop if state ID memory is somehow corrupted.
        }
    }
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state ROOT
////////////////////////////////////////////////////////////////////////////////

static void ROOT_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_ROOT;
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state ABORTSTATE
////////////////////////////////////////////////////////////////////////////////

static void ABORTSTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_ABORTSTATE;
    
    // abortState behavior
    // uml: enter
    {
        // Step 1: execute action ``
    } // end of behavior for abortState
}

static void ABORTSTATE_exit(tracingStateMachine* sm)
{
    // abortState behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for abortState
    
    sm->state_id = tracingStateMachine_StateId_ROOT;
}

static void ABORTSTATE_do(tracingStateMachine* sm)
{
    // abortState behavior
    // uml: do / { abort(); }
    {
        // Step 1: execute action `abort();`
        abort();
    } // end of behavior for abortState
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state ALLPLANNED
////////////////////////////////////////////////////////////////////////////////

static void ALLPLANNED_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_ALLPLANNED;
    
    // allPlanned behavior
    // uml: enter
    {
        // Step 1: execute action ``
    } // end of behavior for allPlanned
}

static void ALLPLANNED_exit(tracingStateMachine* sm)
{
    // allPlanned behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for allPlanned
    
    sm->state_id = tracingStateMachine_StateId_ROOT;
}

static void ALLPLANNED_do(tracingStateMachine* sm)
{
    // allPlanned behavior
    // uml: do
    {
        // Step 1: execute action ``
    } // end of behavior for allPlanned
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state ATTEMPTNEXTCLOSESTSTATE
////////////////////////////////////////////////////////////////////////////////

static void ATTEMPTNEXTCLOSESTSTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_ATTEMPTNEXTCLOSESTSTATE;
    
    // attemptNextClosestState behavior
    // uml: enter / { chosenVector++; }
    {
        // Step 1: execute action `chosenVector++;`
        sm->vars.chosenVector++;
    } // end of behavior for attemptNextClosestState
}

static void ATTEMPTNEXTCLOSESTSTATE_exit(tracingStateMachine* sm)
{
    // attemptNextClosestState behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for attemptNextClosestState
    
    sm->state_id = tracingStateMachine_StateId_ROOT;
}

static void ATTEMPTNEXTCLOSESTSTATE_do(tracingStateMachine* sm)
{
    // attemptNextClosestState behavior
    // uml: do / { attemptToReachNextClosest(); }
    {
        // Step 1: execute action `attemptToReachNextClosest();`
        attemptToReachNextClosest();
    } // end of behavior for attemptNextClosestState
    
    // attemptNextClosestState behavior
    // uml: do [chosenVector > = 3\n&& initialTriangle != AttemptToReach::TRIANGLE_REACHED] TransitionTo(abortState)
    if (sm->vars.chosenVector > = 3&& sm->vars.initialTriangle != AttemptToReach::TRIANGLE_REACHED)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        ATTEMPTNEXTCLOSESTSTATE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `abortState`.
        ABORTSTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for attemptNextClosestState
    
    // attemptNextClosestState behavior
    // uml: do [opSuccess] TransitionTo(leastNeighboursSearchState)
    if (sm->vars.opSuccess)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        ATTEMPTNEXTCLOSESTSTATE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `leastNeighboursSearchState`.
        LEASTNEIGHBOURSSEARCHSTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for attemptNextClosestState
    
    // attemptNextClosestState behavior
    // uml: do [!operationResultCatcher] TransitionTo(getPoseStateInReaching)
    if (!operationResultCatcher)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        ATTEMPTNEXTCLOSESTSTATE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `getPoseStateInReaching`.
        REACHINGSTATE_enter(sm);
        GETPOSESTATEINREACHING_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for attemptNextClosestState
    
    // attemptNextClosestState behavior
    // uml: else do TransitionTo(attemptNextClosestState)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        ATTEMPTNEXTCLOSESTSTATE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `attemptNextClosestState`.
        ATTEMPTNEXTCLOSESTSTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for attemptNextClosestState
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state INITSTATE
////////////////////////////////////////////////////////////////////////////////

static void INITSTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_INITSTATE;
    
    // initState behavior
    // uml: enter / { iterator = 0; }
    {
        // Step 1: execute action `iterator = 0;`
        sm->vars.iterator = 0;
    } // end of behavior for initState
}

static void INITSTATE_exit(tracingStateMachine* sm)
{
    // initState behavior
    // uml: exit / { chosenVector = -1; }
    {
        // Step 1: execute action `chosenVector = -1;`
        sm->vars.chosenVector = -1;
    } // end of behavior for initState
    
    sm->state_id = tracingStateMachine_StateId_ROOT;
}

static void INITSTATE_do(tracingStateMachine* sm)
{
    // initState behavior
    // uml: do / { initialTriangle = AttemptToReach::EMPTY_VECTOR; }
    {
        // Step 1: execute action `initialTriangle = AttemptToReach::EMPTY_VECTOR;`
        sm->vars.initialTriangle = AttemptToReach::EMPTY_VECTOR;
    } // end of behavior for initState
    
    // initState behavior
    // uml: do TransitionTo(attemptNextClosestState)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        INITSTATE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `attemptNextClosestState`.
        ATTEMPTNEXTCLOSESTSTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for initState
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state JUMPTOBRANCHSTATE
////////////////////////////////////////////////////////////////////////////////

static void JUMPTOBRANCHSTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_JUMPTOBRANCHSTATE;
}

static void JUMPTOBRANCHSTATE_exit(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_ROOT;
}

static void jumpToBranchState_ChoicePoint__transition(tracingStateMachine* sm)
{
    // jumpToBranchState.<ChoicePoint>() behavior
    // uml: [stackOfReachableWaypoints.size() > size] TransitionTo(checkSizeState)
    if (stackOfReachableWaypoints.size() > sm->vars.size)
    {
        // Step 1: Exit states until we reach `jumpToBranchState` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `checkSizeState`.
        CHECKSIZESTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for jumpToBranchState.<ChoicePoint>()
    
    // jumpToBranchState.<ChoicePoint>() behavior
    // uml: else TransitionTo(failedJumpState)
    {
        // Step 1: Exit states until we reach `jumpToBranchState` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `failedJumpState`.
        FAILEDJUMPSTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for jumpToBranchState.<ChoicePoint>()
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state CHECKSIZESTATE
////////////////////////////////////////////////////////////////////////////////

static void CHECKSIZESTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_CHECKSIZESTATE;
    
    // checkSizeState behavior
    // uml: enter
    {
        // Step 1: execute action ``
    } // end of behavior for checkSizeState
}

static void CHECKSIZESTATE_exit(tracingStateMachine* sm)
{
    // checkSizeState behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for checkSizeState
    
    sm->state_id = tracingStateMachine_StateId_JUMPTOBRANCHSTATE;
}

static void CHECKSIZESTATE_do(tracingStateMachine* sm)
{
    // checkSizeState behavior
    // uml: do / { stackOfReachableWaypoints.pop(); }
    {
        // Step 1: execute action `stackOfReachableWaypoints.pop();`
        stackOfReachableWaypoints.pop();
    } // end of behavior for checkSizeState
    
    // checkSizeState behavior
    // uml: do TransitionTo(jumpToBranchState.<ChoicePoint>())
    {
        // Step 1: Exit states until we reach `jumpToBranchState` state (Least Common Ancestor for transition).
        CHECKSIZESTATE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `jumpToBranchState.<ChoicePoint>()`.
        // jumpToBranchState.<ChoicePoint>() is a pseudo state and cannot have an `enter` trigger.
        
        // Finish transition by calling pseudo state transition function.
        jumpToBranchState_ChoicePoint__transition(sm);
        return; // event processing immediately stops when a transition finishes. No other behaviors for this state are checked.
    } // end of behavior for checkSizeState
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state FAILEDJUMPSTATE
////////////////////////////////////////////////////////////////////////////////

static void FAILEDJUMPSTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_FAILEDJUMPSTATE;
    
    // failedJumpState behavior
    // uml: enter / { target.unreachableCounter++; }
    {
        // Step 1: execute action `target.unreachableCounter++;`
        sm->vars.target.unreachableCounter++;
    } // end of behavior for failedJumpState
}

static void FAILEDJUMPSTATE_exit(tracingStateMachine* sm)
{
    // failedJumpState behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for failedJumpState
    
    sm->state_id = tracingStateMachine_StateId_JUMPTOBRANCHSTATE;
}

static void FAILEDJUMPSTATE_do(tracingStateMachine* sm)
{
    // failedJumpState behavior
    // uml: do / { opSuccess = clearHistoryGoBack(); }
    {
        // Step 1: execute action `opSuccess = clearHistoryGoBack();`
        sm->vars.opSuccess = clearHistoryGoBack();
    } // end of behavior for failedJumpState
    
    // failedJumpState behavior
    // uml: do TransitionTo(leastNeighboursSearchState)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, tracingStateMachine_StateId_ROOT);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `leastNeighboursSearchState`.
        LEASTNEIGHBOURSSEARCHSTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for failedJumpState
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state GETCANDIDATESSTATE
////////////////////////////////////////////////////////////////////////////////

static void GETCANDIDATESSTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_GETCANDIDATESSTATE;
    
    // getCandidatesState behavior
    // uml: enter
    {
        // Step 1: execute action ``
    } // end of behavior for getCandidatesState
}

static void GETCANDIDATESSTATE_exit(tracingStateMachine* sm)
{
    // getCandidatesState behavior
    // uml: exit / { iterator = -1; }
    {
        // Step 1: execute action `iterator = -1;`
        sm->vars.iterator = -1;
    } // end of behavior for getCandidatesState
    
    sm->state_id = tracingStateMachine_StateId_JUMPTOBRANCHSTATE;
}

static void GETCANDIDATESSTATE_do(tracingStateMachine* sm)
{
    // getCandidatesState behavior
    // uml: do / { candidates = getBranchCandidates(); }
    {
        // Step 1: execute action `candidates = getBranchCandidates();`
        sm->vars.candidates = getBranchCandidates();
    } // end of behavior for getCandidatesState
    
    // getCandidatesState behavior
    // uml: do TransitionTo(triangSetupState)
    {
        // Step 1: Exit states until we reach `jumpToBranchState` state (Least Common Ancestor for transition).
        GETCANDIDATESSTATE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `triangSetupState`.
        JUMPTOTRIANGLESTATE_enter(sm);
        TRIANGSETUPSTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for getCandidatesState
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state JUMPTOTRIANGLESTATE
////////////////////////////////////////////////////////////////////////////////

static void JUMPTOTRIANGLESTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_JUMPTOTRIANGLESTATE;
}

static void JUMPTOTRIANGLESTATE_exit(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_JUMPTOBRANCHSTATE;
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state FAIL
////////////////////////////////////////////////////////////////////////////////

static void FAIL_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_FAIL;
}

static void FAIL_exit(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_JUMPTOTRIANGLESTATE;
}

static void FAIL_do(tracingStateMachine* sm)
{
    // fail behavior
    // uml: do TransitionTo(jumpToBranchState.<ChoicePoint>())
    {
        // Step 1: Exit states until we reach `jumpToBranchState` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, tracingStateMachine_StateId_JUMPTOBRANCHSTATE);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `jumpToBranchState.<ChoicePoint>()`.
        // jumpToBranchState.<ChoicePoint>() is a pseudo state and cannot have an `enter` trigger.
        
        // Finish transition by calling pseudo state transition function.
        jumpToBranchState_ChoicePoint__transition(sm);
        return; // event processing immediately stops when a transition finishes. No other behaviors for this state are checked.
    } // end of behavior for fail
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state FALLBACKPREPSTATE
////////////////////////////////////////////////////////////////////////////////

static void FALLBACKPREPSTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_FALLBACKPREPSTATE;
    
    // fallbackPrepState behavior
    // uml: enter / { size = stackOfReachableWaypoints.size(); }
    {
        // Step 1: execute action `size = stackOfReachableWaypoints.size();`
        sm->vars.size = stackOfReachableWaypoints.size(); 
    } // end of behavior for fallbackPrepState
}

static void FALLBACKPREPSTATE_exit(tracingStateMachine* sm)
{
    // fallbackPrepState behavior
    // uml: exit / { if(!currentState){\nopSuccess = 0;} }
    {
        // Step 1: execute action `if(!currentState){\nopSuccess = 0;}`
        if(!sm->vars.currentState){
        sm->vars.opSuccess = 0;}
    } // end of behavior for fallbackPrepState
    
    sm->state_id = tracingStateMachine_StateId_JUMPTOTRIANGLESTATE;
}

static void FALLBACKPREPSTATE_do(tracingStateMachine* sm)
{
    // fallbackPrepState behavior
    // uml: do / { currentState = gripper_group_interface->getCurrentState(); }
    {
        // Step 1: execute action `currentState = gripper_group_interface->getCurrentState();`
        sm->vars.currentState = gripper_group_interface->getCurrentState();
    } // end of behavior for fallbackPrepState
    
    // fallbackPrepState behavior
    // uml: do [!currentState] TransitionTo(leastNeighboursSearchState)
    if (!sm->vars.currentState)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, tracingStateMachine_StateId_ROOT);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `leastNeighboursSearchState`.
        LEASTNEIGHBOURSSEARCHSTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for fallbackPrepState
    
    // fallbackPrepState behavior
    // uml: else do TransitionTo(liftedPoseStarightLineState)
    {
        // Step 1: Exit states until we reach `jumpToTriangleState` state (Least Common Ancestor for transition).
        FALLBACKPREPSTATE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `liftedPoseStarightLineState`.
        LIFTEDPOSESTARIGHTLINESTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for fallbackPrepState
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state LIFTEDPOSERANDOMTRAJSTATE
////////////////////////////////////////////////////////////////////////////////

static void LIFTEDPOSERANDOMTRAJSTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_LIFTEDPOSERANDOMTRAJSTATE;
    
    // liftedPoseRandomTrajState behavior
    // uml: enter / { target_pose = liftedPose(currentTriangle); }
    {
        // Step 1: execute action `target_pose = liftedPose(currentTriangle);`
        sm->vars.target_pose = liftedPose(sm->vars.currentTriangle);
    } // end of behavior for liftedPoseRandomTrajState
}

static void LIFTEDPOSERANDOMTRAJSTATE_exit(tracingStateMachine* sm)
{
    // liftedPoseRandomTrajState behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for liftedPoseRandomTrajState
    
    sm->state_id = tracingStateMachine_StateId_JUMPTOTRIANGLESTATE;
}

static void LIFTEDPOSERANDOMTRAJSTATE_do(tracingStateMachine* sm)
{
    // liftedPoseRandomTrajState behavior
    // uml: do / { opSuccess = planOMPLPose(\ntarget_pose, \ncurrentTriangle.myIndex\n); }
    {
        // Step 1: execute action `opSuccess = planOMPLPose(\ntarget_pose, \ncurrentTriangle.myIndex\n);`
        sm->vars.opSuccess = planOMPLPose(
        sm->vars.target_pose, 
        sm->vars.currentTriangle.myIndex
        );
    } // end of behavior for liftedPoseRandomTrajState
    
    // liftedPoseRandomTrajState behavior
    // uml: do [!opSuccess] TransitionTo(fail)
    if (!sm->vars.opSuccess)
    {
        // Step 1: Exit states until we reach `jumpToTriangleState` state (Least Common Ancestor for transition).
        LIFTEDPOSERANDOMTRAJSTATE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `fail`.
        FAIL_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for liftedPoseRandomTrajState
    
    // liftedPoseRandomTrajState behavior
    // uml: else do TransitionTo(targetPoseStraightLineState)
    {
        // Step 1: Exit states until we reach `jumpToTriangleState` state (Least Common Ancestor for transition).
        LIFTEDPOSERANDOMTRAJSTATE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `targetPoseStraightLineState`.
        TARGETPOSESTRAIGHTLINESTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for liftedPoseRandomTrajState
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state LIFTEDPOSESTARIGHTLINESTATE
////////////////////////////////////////////////////////////////////////////////

static void LIFTEDPOSESTARIGHTLINESTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_LIFTEDPOSESTARIGHTLINESTATE;
    
    // liftedPoseStarightLineState behavior
    // uml: enter / { moveit::core::RobotState savedState(*current_state_ptr);\ntarget_pose = liftedPose(previousTriangle); }
    {
        // Step 1: execute action `moveit::core::RobotState savedState(*current_state_ptr);\ntarget_pose = liftedPose(previousTriangle);`
        moveit::core::RobotState savedState(*current_state_ptr);
        sm->vars.target_pose = liftedPose(sm->vars.previousTriangle);
    } // end of behavior for liftedPoseStarightLineState
}

static void LIFTEDPOSESTARIGHTLINESTATE_exit(tracingStateMachine* sm)
{
    // liftedPoseStarightLineState behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for liftedPoseStarightLineState
    
    sm->state_id = tracingStateMachine_StateId_JUMPTOTRIANGLESTATE;
}

static void LIFTEDPOSESTARIGHTLINESTATE_do(tracingStateMachine* sm)
{
    // liftedPoseStarightLineState behavior
    // uml: do / { opSuccess = moveToPoint(\ntarget_pose, \npreviousTriangle.myIndex, \nmovementDirection::BACKWARDS\n); }
    {
        // Step 1: execute action `opSuccess = moveToPoint(\ntarget_pose, \npreviousTriangle.myIndex, \nmovementDirection::BACKWARDS\n);`
        sm->vars.opSuccess = moveToPoint(
        sm->vars.target_pose, 
        sm->vars.previousTriangle.myIndex, 
        movementDirection::BACKWARDS
        );
    } // end of behavior for liftedPoseStarightLineState
    
    // liftedPoseStarightLineState behavior
    // uml: do [!opSuccess] TransitionTo(fail)
    if (!sm->vars.opSuccess)
    {
        // Step 1: Exit states until we reach `jumpToTriangleState` state (Least Common Ancestor for transition).
        LIFTEDPOSESTARIGHTLINESTATE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `fail`.
        FAIL_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for liftedPoseStarightLineState
    
    // liftedPoseStarightLineState behavior
    // uml: else do TransitionTo(liftedPoseRandomTrajState)
    {
        // Step 1: Exit states until we reach `jumpToTriangleState` state (Least Common Ancestor for transition).
        LIFTEDPOSESTARIGHTLINESTATE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `liftedPoseRandomTrajState`.
        LIFTEDPOSERANDOMTRAJSTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for liftedPoseStarightLineState
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state MOVEWITHLIFTSTATE
////////////////////////////////////////////////////////////////////////////////

static void MOVEWITHLIFTSTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_MOVEWITHLIFTSTATE;
    
    // moveWithLiftState behavior
    // uml: enter / { targetPose(target); }
    {
        // Step 1: execute action `targetPose(target);`
        targetPose(sm->vars.target);
    } // end of behavior for moveWithLiftState
}

static void MOVEWITHLIFTSTATE_exit(tracingStateMachine* sm)
{
    // moveWithLiftState behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for moveWithLiftState
    
    sm->state_id = tracingStateMachine_StateId_JUMPTOTRIANGLESTATE;
}

static void MOVEWITHLIFTSTATE_do(tracingStateMachine* sm)
{
    // moveWithLiftState behavior
    // uml: do / { opSuccess = \nmoverToPoint(\ntarget_pose, \ntarget.myIndex,\nmovementDirection::FORWARD, \nwaypointType::TRIANGLE,\n{liftedPose(previousTriangle), liftedPose(target)}\n); }
    {
        // Step 1: execute action `opSuccess = \nmoverToPoint(\ntarget_pose, \ntarget.myIndex,\nmovementDirection::FORWARD, \nwaypointType::TRIANGLE,\n{liftedPose(previousTriangle), liftedPose(target)}\n);`
        sm->vars.opSuccess = 
        moverToPoint(
        sm->vars.target_pose, 
        sm->vars.target.myIndex,
        movementDirection::FORWARD, 
        waypointType::TRIANGLE,
        {liftedPose(sm->vars.previousTriangle), liftedPose(sm->vars.target)}
        );
    } // end of behavior for moveWithLiftState
    
    // moveWithLiftState behavior
    // uml: do [!opSuccess] TransitionTo(fallbackPrepState)
    if (!sm->vars.opSuccess)
    {
        // Step 1: Exit states until we reach `jumpToTriangleState` state (Least Common Ancestor for transition).
        MOVEWITHLIFTSTATE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `fallbackPrepState`.
        FALLBACKPREPSTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for moveWithLiftState
    
    // moveWithLiftState behavior
    // uml: else do TransitionTo(successfulJumpState)
    {
        // Step 1: Exit states until we reach `jumpToBranchState` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, tracingStateMachine_StateId_JUMPTOBRANCHSTATE);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `successfulJumpState`.
        SUCCESSFULJUMPSTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for moveWithLiftState
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state TARGETPOSESTRAIGHTLINESTATE
////////////////////////////////////////////////////////////////////////////////

static void TARGETPOSESTRAIGHTLINESTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_TARGETPOSESTRAIGHTLINESTATE;
    
    // targetPoseStraightLineState behavior
    // uml: enter / { targetPose(currentTriangle); }
    {
        // Step 1: execute action `targetPose(currentTriangle);`
        targetPose(sm->vars.currentTriangle);
    } // end of behavior for targetPoseStraightLineState
}

static void TARGETPOSESTRAIGHTLINESTATE_exit(tracingStateMachine* sm)
{
    // targetPoseStraightLineState behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for targetPoseStraightLineState
    
    sm->state_id = tracingStateMachine_StateId_JUMPTOTRIANGLESTATE;
}

static void TARGETPOSESTRAIGHTLINESTATE_do(tracingStateMachine* sm)
{
    // targetPoseStraightLineState behavior
    // uml: do / { oparationSuccessCatcher = moveToPoint(\ntarget_pose, \ncurrentTriangle.myIndex, \nmovementDirection::FORWARD\n); }
    {
        // Step 1: execute action `oparationSuccessCatcher = moveToPoint(\ntarget_pose, \ncurrentTriangle.myIndex, \nmovementDirection::FORWARD\n);`
        oparationSuccessCatcher = moveToPoint(
        sm->vars.target_pose, 
        sm->vars.currentTriangle.myIndex, 
        movementDirection::FORWARD
        );
    } // end of behavior for targetPoseStraightLineState
    
    // targetPoseStraightLineState behavior
    // uml: do [!opSuccess] TransitionTo(fail)
    if (!sm->vars.opSuccess)
    {
        // Step 1: Exit states until we reach `jumpToTriangleState` state (Least Common Ancestor for transition).
        TARGETPOSESTRAIGHTLINESTATE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `fail`.
        FAIL_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for targetPoseStraightLineState
    
    // targetPoseStraightLineState behavior
    // uml: else do TransitionTo(successfulJumpState)
    {
        // Step 1: Exit states until we reach `jumpToBranchState` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, tracingStateMachine_StateId_JUMPTOBRANCHSTATE);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `successfulJumpState`.
        SUCCESSFULJUMPSTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for targetPoseStraightLineState
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state TRIANGSETUPSTATE
////////////////////////////////////////////////////////////////////////////////

static void TRIANGSETUPSTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_TRIANGSETUPSTATE;
    
    // triangSetupState behavior
    // uml: enter / { iterator++; }
    {
        // Step 1: execute action `iterator++;`
        sm->vars.iterator++;
    } // end of behavior for triangSetupState
}

static void TRIANGSETUPSTATE_exit(tracingStateMachine* sm)
{
    // triangSetupState behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for triangSetupState
    
    sm->state_id = tracingStateMachine_StateId_JUMPTOTRIANGLESTATE;
}

static void TRIANGSETUPSTATE_do(tracingStateMachine* sm)
{
    // triangSetupState behavior
    // uml: do / { previousTriangle = currentTriangle;\ntarget = vectorOfTriangles[candidates[iterator]]; }
    {
        // Step 1: execute action `previousTriangle = currentTriangle;\ntarget = vectorOfTriangles[candidates[iterator]];`
        sm->vars.previousTriangle = sm->vars.currentTriangle;
        sm->vars.target = sm->vars.vectorOfTriangles[sm->vars.candidates[sm->vars.iterator]];
    } // end of behavior for triangSetupState
    
    // triangSetupState behavior
    // uml: do TransitionTo(moveWithLiftState)
    {
        // Step 1: Exit states until we reach `jumpToTriangleState` state (Least Common Ancestor for transition).
        TRIANGSETUPSTATE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `moveWithLiftState`.
        MOVEWITHLIFTSTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for triangSetupState
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state SUCCESSFULJUMPSTATE
////////////////////////////////////////////////////////////////////////////////

static void SUCCESSFULJUMPSTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_SUCCESSFULJUMPSTATE;
    
    // successfulJumpState behavior
    // uml: enter
    {
        // Step 1: execute action ``
    } // end of behavior for successfulJumpState
}

static void SUCCESSFULJUMPSTATE_exit(tracingStateMachine* sm)
{
    // successfulJumpState behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for successfulJumpState
    
    sm->state_id = tracingStateMachine_StateId_JUMPTOBRANCHSTATE;
}

static void SUCCESSFULJUMPSTATE_do(tracingStateMachine* sm)
{
    // successfulJumpState behavior
    // uml: do / { currentTriangle = target; }
    {
        // Step 1: execute action `currentTriangle = target;`
        sm->vars.currentTriangle = sm->vars.target;
    } // end of behavior for successfulJumpState
    
    // successfulJumpState behavior
    // uml: do TransitionTo(leastNeighboursSearchState)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, tracingStateMachine_StateId_ROOT);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `leastNeighboursSearchState`.
        LEASTNEIGHBOURSSEARCHSTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for successfulJumpState
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state LEASTNEIGHBOURSSEARCHSTATE
////////////////////////////////////////////////////////////////////////////////

static void LEASTNEIGHBOURSSEARCHSTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_LEASTNEIGHBOURSSEARCHSTATE;
    
    // leastNeighboursSearchState behavior
    // uml: enter / { if(pathHistory.empty() && stackOfReachableWaypoints.empty()){\nbranchPoints.clear();} }
    {
        // Step 1: execute action `if(pathHistory.empty() && stackOfReachableWaypoints.empty()){\nbranchPoints.clear();}`
        if(pathHistory.empty() && stackOfReachableWaypoints.empty()){
        branchPoints.clear();}
    } // end of behavior for leastNeighboursSearchState
}

static void LEASTNEIGHBOURSSEARCHSTATE_exit(tracingStateMachine* sm)
{
    // leastNeighboursSearchState behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for leastNeighboursSearchState
    
    sm->state_id = tracingStateMachine_StateId_ROOT;
}

static void LEASTNEIGHBOURSSEARCHSTATE_do(tracingStateMachine* sm)
{
    // leastNeighboursSearchState behavior
    // uml: do / { result = triangleWithLeastNeighbours(); }
    {
        // Step 1: execute action `result = triangleWithLeastNeighbours();`
        sm->vars.result = triangleWithLeastNeighbours();
    } // end of behavior for leastNeighboursSearchState
    
    // leastNeighboursSearchState behavior
    // uml: do [!result.first.empty() &&\n!result.second.empty() &&\nopSuccess] TransitionTo(moveToEdgeState)
    if (!sm->vars.result.first.empty() &&!sm->vars.result.second.empty() &&sm->vars.opSuccess)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        LEASTNEIGHBOURSSEARCHSTATE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `moveToEdgeState`.
        TRACENEIGHBOURSTATE_enter(sm);
        MOVETOEDGESTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for leastNeighboursSearchState
    
    // leastNeighboursSearchState behavior
    // uml: do [( result.first.empty() ||\nresult.second.empty() )&&\nopSuccess] TransitionTo(getCandidatesState)
    if (( sm->vars.result.first.empty() ||sm->vars.result.second.empty() )&&sm->vars.opSuccess)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        LEASTNEIGHBOURSSEARCHSTATE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `getCandidatesState`.
        JUMPTOBRANCHSTATE_enter(sm);
        GETCANDIDATESSTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for leastNeighboursSearchState
    
    // leastNeighboursSearchState behavior
    // uml: do [!opSuccess] TransitionTo(allPlanned)
    if (!sm->vars.opSuccess)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        LEASTNEIGHBOURSSEARCHSTATE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `allPlanned`.
        ALLPLANNED_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for leastNeighboursSearchState
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state REACHINGSTATE
////////////////////////////////////////////////////////////////////////////////

static void REACHINGSTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_REACHINGSTATE;
}

static void REACHINGSTATE_exit(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_ROOT;
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state GETCLOSESTSTATE
////////////////////////////////////////////////////////////////////////////////

static void GETCLOSESTSTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_GETCLOSESTSTATE;
    
    // getClosestState behavior
    // uml: enter
    {
        // Step 1: execute action ``
    } // end of behavior for getClosestState
}

static void GETCLOSESTSTATE_exit(tracingStateMachine* sm)
{
    // getClosestState behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for getClosestState
    
    sm->state_id = tracingStateMachine_StateId_REACHINGSTATE;
}

static void GETCLOSESTSTATE_do(tracingStateMachine* sm)
{
    // getClosestState behavior
    // uml: do / { closestTriangle = getClosestTriangle();\ntarget = vectorOfDesiredTriangles[closestTriangle] }
    {
        // Step 1: execute action `closestTriangle = getClosestTriangle();\ntarget = vectorOfDesiredTriangles[closestTriangle]`
        sm->vars.closestTriangle = getClosestTriangle();
        sm->vars.target = sm->vars.vectorOfDesiredTriangles[sm->vars.closestTriangle]
    } // end of behavior for getClosestState
    
    // getClosestState behavior
    // uml: do TransitionTo(moveStateInReaching)
    {
        // Step 1: Exit states until we reach `reachingState` state (Least Common Ancestor for transition).
        GETCLOSESTSTATE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `moveStateInReaching`.
        MOVESTATEINREACHING_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for getClosestState
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state GETPOSESTATEINREACHING
////////////////////////////////////////////////////////////////////////////////

static void GETPOSESTATEINREACHING_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_GETPOSESTATEINREACHING;
    
    // getPoseStateInReaching behavior
    // uml: enter
    {
        // Step 1: execute action ``
    } // end of behavior for getPoseStateInReaching
}

static void GETPOSESTATEINREACHING_exit(tracingStateMachine* sm)
{
    // getPoseStateInReaching behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for getPoseStateInReaching
    
    sm->state_id = tracingStateMachine_StateId_REACHINGSTATE;
}

static void GETPOSESTATEINREACHING_do(tracingStateMachine* sm)
{
    // getPoseStateInReaching behavior
    // uml: do / { opSuccess = getTCPpose(); }
    {
        // Step 1: execute action `opSuccess = getTCPpose();`
        sm->vars.opSuccess = getTCPpose();
    } // end of behavior for getPoseStateInReaching
    
    // getPoseStateInReaching behavior
    // uml: do [opSuccess] TransitionTo(getClosestState)
    if (sm->vars.opSuccess)
    {
        // Step 1: Exit states until we reach `reachingState` state (Least Common Ancestor for transition).
        GETPOSESTATEINREACHING_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `getClosestState`.
        GETCLOSESTSTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for getPoseStateInReaching
    
    // getPoseStateInReaching behavior
    // uml: do [!opSuccess] TransitionTo(abortState)
    if (!sm->vars.opSuccess)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, tracingStateMachine_StateId_ROOT);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `abortState`.
        ABORTSTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for getPoseStateInReaching
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state MOVESTATEINREACHING
////////////////////////////////////////////////////////////////////////////////

static void MOVESTATEINREACHING_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_MOVESTATEINREACHING;
    
    // moveStateInReaching behavior
    // uml: enter
    {
        // Step 1: execute action ``
    } // end of behavior for moveStateInReaching
}

static void MOVESTATEINREACHING_exit(tracingStateMachine* sm)
{
    // moveStateInReaching behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for moveStateInReaching
    
    sm->state_id = tracingStateMachine_StateId_REACHINGSTATE;
}

static void MOVESTATEINREACHING_do(tracingStateMachine* sm)
{
    // moveStateInReaching behavior
    // uml: do / { targetPose();\nopSuccess  = moveToPoint();\niterator++; }
    {
        // Step 1: execute action `targetPose();\nopSuccess  = moveToPoint();\niterator++;`
        targetPose();
        sm->vars.opSuccess  = moveToPoint();
        sm->vars.iterator++;
    } // end of behavior for moveStateInReaching
    
    // moveStateInReaching behavior
    // uml: do [!opSuccess] TransitionTo(reachFailed)
    if (!sm->vars.opSuccess)
    {
        // Step 1: Exit states until we reach `reachingState` state (Least Common Ancestor for transition).
        MOVESTATEINREACHING_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `reachFailed`.
        REACHFAILED_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for moveStateInReaching
    
    // moveStateInReaching behavior
    // uml: do [opSuccess] TransitionTo(attemptNextClosestState)
    if (sm->vars.opSuccess)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, tracingStateMachine_StateId_ROOT);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `attemptNextClosestState`.
        ATTEMPTNEXTCLOSESTSTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for moveStateInReaching
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state REACHFAILED
////////////////////////////////////////////////////////////////////////////////

static void REACHFAILED_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_REACHFAILED;
    
    // reachFailed behavior
    // uml: enter
    {
        // Step 1: execute action ``
    } // end of behavior for reachFailed
}

static void REACHFAILED_exit(tracingStateMachine* sm)
{
    // reachFailed behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for reachFailed
    
    sm->state_id = tracingStateMachine_StateId_REACHINGSTATE;
}

static void REACHFAILED_do(tracingStateMachine* sm)
{
    // reachFailed behavior
    // uml: do / { vectorOfDesiredTriangles[closestTriangle].unreachableCounter++;\nvectorOfDesiredTriangles.erase(vectorOfDesiredTriangles.begin() + closestTriangle); }
    {
        // Step 1: execute action `vectorOfDesiredTriangles[closestTriangle].unreachableCounter++;\nvectorOfDesiredTriangles.erase(vectorOfDesiredTriangles.begin() + closestTriangle);`
        sm->vars.vectorOfDesiredTriangles[sm->vars.closestTriangle].unreachableCounter++;
        sm->vars.vectorOfDesiredTriangles.erase(sm->vars.vectorOfDesiredTriangles.begin() + sm->vars.closestTriangle);
    } // end of behavior for reachFailed
    
    // reachFailed behavior
    // uml: do [iterator < \ndesiredVectorSize] TransitionTo(getClosestState)
    if (sm->vars.iterator < sm->vars.desiredVectorSize)
    {
        // Step 1: Exit states until we reach `reachingState` state (Least Common Ancestor for transition).
        REACHFAILED_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `getClosestState`.
        GETCLOSESTSTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for reachFailed
    
    // reachFailed behavior
    // uml: else do TransitionTo(attemptNextClosestState)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, tracingStateMachine_StateId_ROOT);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `attemptNextClosestState`.
        ATTEMPTNEXTCLOSESTSTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for reachFailed
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state TRACENEIGHBOURSTATE
////////////////////////////////////////////////////////////////////////////////

static void TRACENEIGHBOURSTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_TRACENEIGHBOURSTATE;
}

static void TRACENEIGHBOURSTATE_exit(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_ROOT;
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state FINISHTRANSBETWEENTRIANGLESSTATE
////////////////////////////////////////////////////////////////////////////////

static void FINISHTRANSBETWEENTRIANGLESSTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_FINISHTRANSBETWEENTRIANGLESSTATE;
    
    // finishTransBetweenTrianglesState behavior
    // uml: enter
    {
        // Step 1: execute action ``
    } // end of behavior for finishTransBetweenTrianglesState
}

static void FINISHTRANSBETWEENTRIANGLESSTATE_exit(tracingStateMachine* sm)
{
    // finishTransBetweenTrianglesState behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for finishTransBetweenTrianglesState
    
    sm->state_id = tracingStateMachine_StateId_TRACENEIGHBOURSTATE;
}

static void FINISHTRANSBETWEENTRIANGLESSTATE_do(tracingStateMachine* sm)
{
    // finishTransBetweenTrianglesState behavior
    // uml: do / { currentTriangle.traced = true;\ntraced[currentTriangle.myIndex] = true;\ncurrentTriangle = result.first[iterator];\niterator = 0;\nrememberBranchPoint(); }
    {
        // Step 1: execute action `currentTriangle.traced = true;\ntraced[currentTriangle.myIndex] = true;\ncurrentTriangle = result.first[iterator];\niterator = 0;\nrememberBranchPoint();`
        sm->vars.currentTriangle.traced = true;
        sm->vars.traced[sm->vars.currentTriangle.myIndex] = true;
        sm->vars.currentTriangle = sm->vars.result.first[sm->vars.iterator];
        sm->vars.iterator = 0;
        rememberBranchPoint();
    } // end of behavior for finishTransBetweenTrianglesState
    
    // finishTransBetweenTrianglesState behavior
    // uml: do TransitionTo(leastNeighboursSearchState)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, tracingStateMachine_StateId_ROOT);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `leastNeighboursSearchState`.
        LEASTNEIGHBOURSSEARCHSTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for finishTransBetweenTrianglesState
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state MOVEFROMEDGESTATE
////////////////////////////////////////////////////////////////////////////////

static void MOVEFROMEDGESTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_MOVEFROMEDGESTATE;
    
    // moveFromEdgeState behavior
    // uml: enter / { targetPose(currentTriangle); }
    {
        // Step 1: execute action `targetPose(currentTriangle);`
        targetPose(sm->vars.currentTriangle);
    } // end of behavior for moveFromEdgeState
}

static void MOVEFROMEDGESTATE_exit(tracingStateMachine* sm)
{
    // moveFromEdgeState behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for moveFromEdgeState
    
    sm->state_id = tracingStateMachine_StateId_TRACENEIGHBOURSTATE;
}

static void MOVEFROMEDGESTATE_do(tracingStateMachine* sm)
{
    // moveFromEdgeState behavior
    // uml: do / { opSuccess = moveToPoint(); }
    {
        // Step 1: execute action `opSuccess = moveToPoint();`
        sm->vars.opSuccess = moveToPoint();
    } // end of behavior for moveFromEdgeState
    
    // moveFromEdgeState behavior
    // uml: do [!opSuccess] TransitionTo(popHistroryAndMoveBackState)
    if (!sm->vars.opSuccess)
    {
        // Step 1: Exit states until we reach `traceNeighbourState` state (Least Common Ancestor for transition).
        MOVEFROMEDGESTATE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `popHistroryAndMoveBackState`.
        POPHISTRORYANDMOVEBACKSTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for moveFromEdgeState
    
    // moveFromEdgeState behavior
    // uml: else do TransitionTo(finishTransBetweenTrianglesState)
    {
        // Step 1: Exit states until we reach `traceNeighbourState` state (Least Common Ancestor for transition).
        MOVEFROMEDGESTATE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `finishTransBetweenTrianglesState`.
        FINISHTRANSBETWEENTRIANGLESSTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for moveFromEdgeState
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state MOVETOEDGESTATE
////////////////////////////////////////////////////////////////////////////////

static void MOVETOEDGESTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_MOVETOEDGESTATE;
    
    // moveToEdgeState behavior
    // uml: enter
    {
        // Step 1: execute action ``
    } // end of behavior for moveToEdgeState
}

static void MOVETOEDGESTATE_exit(tracingStateMachine* sm)
{
    // moveToEdgeState behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for moveToEdgeState
    
    sm->state_id = tracingStateMachine_StateId_TRACENEIGHBOURSTATE;
}

static void MOVETOEDGESTATE_do(tracingStateMachine* sm)
{
    // moveToEdgeState behavior
    // uml: do / { setupPose(oldPose);\nopSuccess  = moveToPoint(); }
    {
        // Step 1: execute action `setupPose(oldPose);\nopSuccess  = moveToPoint();`
        setupPose(sm->vars.oldPose);
        sm->vars.opSuccess  = moveToPoint();
    } // end of behavior for moveToEdgeState
    
    // moveToEdgeState behavior
    // uml: do [opSuccess] TransitionTo(rotateAroundEdgeState)
    if (sm->vars.opSuccess)
    {
        // Step 1: Exit states until we reach `traceNeighbourState` state (Least Common Ancestor for transition).
        MOVETOEDGESTATE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `rotateAroundEdgeState`.
        ROTATEAROUNDEDGESTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for moveToEdgeState
    
    // moveToEdgeState behavior
    // uml: do [iterator > ((int)result.first.size() - 1)] TransitionTo(getCandidatesState)
    if (sm->vars.iterator > ((int)sm->vars.result.first.size() - 1))
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, tracingStateMachine_StateId_ROOT);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `getCandidatesState`.
        JUMPTOBRANCHSTATE_enter(sm);
        GETCANDIDATESSTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for moveToEdgeState
    
    // moveToEdgeState behavior
    // uml: else do TransitionTo(updValsOnFailState)
    {
        // Step 1: Exit states until we reach `traceNeighbourState` state (Least Common Ancestor for transition).
        MOVETOEDGESTATE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `updValsOnFailState`.
        UPDVALSONFAILSTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for moveToEdgeState
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state POPHISTRORYANDMOVEBACKSTATE
////////////////////////////////////////////////////////////////////////////////

static void POPHISTRORYANDMOVEBACKSTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_POPHISTRORYANDMOVEBACKSTATE;
    
    // popHistroryAndMoveBackState behavior
    // uml: enter
    {
        // Step 1: execute action ``
    } // end of behavior for popHistroryAndMoveBackState
}

static void POPHISTRORYANDMOVEBACKSTATE_exit(tracingStateMachine* sm)
{
    // popHistroryAndMoveBackState behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for popHistroryAndMoveBackState
    
    sm->state_id = tracingStateMachine_StateId_TRACENEIGHBOURSTATE;
}

static void POPHISTRORYANDMOVEBACKSTATE_do(tracingStateMachine* sm)
{
    // popHistroryAndMoveBackState behavior
    // uml: do / { if(!pathHistory.empty() &&\n                    pathHistory.top().typeOfWaypoint == waypointType::EDGE)\n                    {\n                            pathHistory.pop(); \n         }\ntargetPose(previousTriangle);\nmoveToPoint(); }
    {
        // Step 1: execute action `if(!pathHistory.empty() &&\n                    pathHistory.top().typeOfWaypoint == waypointType::EDGE)\n                    {\n                            pathHistory.pop(); \n         }\ntargetPose(previousTriangle);\nmoveToPoint();`
        if(!pathHistory.empty() &&
                            pathHistory.top().typeOfWaypoint == waypointType::EDGE)
                            {
                                    pathHistory.pop(); 
                 }
        targetPose(sm->vars.previousTriangle);
        moveToPoint();
    } // end of behavior for popHistroryAndMoveBackState
    
    // popHistroryAndMoveBackState behavior
    // uml: do TransitionTo(updValsOnFailState)
    {
        // Step 1: Exit states until we reach `traceNeighbourState` state (Least Common Ancestor for transition).
        POPHISTRORYANDMOVEBACKSTATE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `updValsOnFailState`.
        UPDVALSONFAILSTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for popHistroryAndMoveBackState
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state ROTATEAROUNDEDGESTATE
////////////////////////////////////////////////////////////////////////////////

static void ROTATEAROUNDEDGESTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_ROTATEAROUNDEDGESTATE;
    
    // rotateAroundEdgeState behavior
    // uml: enter / { targetPose(previousTriangle);\nedgeTipPose(); }
    {
        // Step 1: execute action `targetPose(previousTriangle);\nedgeTipPose();`
        targetPose(sm->vars.previousTriangle);
        edgeTipPose();
    } // end of behavior for rotateAroundEdgeState
}

static void ROTATEAROUNDEDGESTATE_exit(tracingStateMachine* sm)
{
    // rotateAroundEdgeState behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for rotateAroundEdgeState
    
    sm->state_id = tracingStateMachine_StateId_TRACENEIGHBOURSTATE;
}

static void ROTATEAROUNDEDGESTATE_do(tracingStateMachine* sm)
{
    // rotateAroundEdgeState behavior
    // uml: do / { opSuccess = moveToPointWithPenRotation(); }
    {
        // Step 1: execute action `opSuccess = moveToPointWithPenRotation();`
        sm->vars.opSuccess = moveToPointWithPenRotation();
    } // end of behavior for rotateAroundEdgeState
    
    // rotateAroundEdgeState behavior
    // uml: do [!opSuccess] TransitionTo(popHistroryAndMoveBackState)
    if (!sm->vars.opSuccess)
    {
        // Step 1: Exit states until we reach `traceNeighbourState` state (Least Common Ancestor for transition).
        ROTATEAROUNDEDGESTATE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `popHistroryAndMoveBackState`.
        POPHISTRORYANDMOVEBACKSTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for rotateAroundEdgeState
    
    // rotateAroundEdgeState behavior
    // uml: else do TransitionTo(moveFromEdgeState)
    {
        // Step 1: Exit states until we reach `traceNeighbourState` state (Least Common Ancestor for transition).
        ROTATEAROUNDEDGESTATE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `moveFromEdgeState`.
        MOVEFROMEDGESTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for rotateAroundEdgeState
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state UPDVALSONFAILSTATE
////////////////////////////////////////////////////////////////////////////////

static void UPDVALSONFAILSTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_UPDVALSONFAILSTATE;
    
    // updValsOnFailState behavior
    // uml: enter / { iterator++;\nneighboutNumber++;\ncurrentTriangle.unreachableCounter++; }
    {
        // Step 1: execute action `iterator++;\nneighboutNumber++;\ncurrentTriangle.unreachableCounter++;`
        sm->vars.iterator++;
        neighboutNumber++;
        sm->vars.currentTriangle.unreachableCounter++;
    } // end of behavior for updValsOnFailState
}

static void UPDVALSONFAILSTATE_exit(tracingStateMachine* sm)
{
    // updValsOnFailState behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for updValsOnFailState
    
    sm->state_id = tracingStateMachine_StateId_TRACENEIGHBOURSTATE;
}

static void UPDVALSONFAILSTATE_do(tracingStateMachine* sm)
{
    // updValsOnFailState behavior
    // uml: do
    {
        // Step 1: execute action ``
    } // end of behavior for updValsOnFailState
    
    // updValsOnFailState behavior
    // uml: do TransitionTo(moveToEdgeState)
    {
        // Step 1: Exit states until we reach `traceNeighbourState` state (Least Common Ancestor for transition).
        UPDVALSONFAILSTATE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `moveToEdgeState`.
        MOVETOEDGESTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for updValsOnFailState
    
    // No ancestor handles this event.
}

// Thread safe.
char const * tracingStateMachine_state_id_to_string(tracingStateMachine_StateId id)
{
    switch (id)
    {
        case tracingStateMachine_StateId_ROOT: return "ROOT";
        case tracingStateMachine_StateId_ABORTSTATE: return "ABORTSTATE";
        case tracingStateMachine_StateId_ALLPLANNED: return "ALLPLANNED";
        case tracingStateMachine_StateId_ATTEMPTNEXTCLOSESTSTATE: return "ATTEMPTNEXTCLOSESTSTATE";
        case tracingStateMachine_StateId_INITSTATE: return "INITSTATE";
        case tracingStateMachine_StateId_JUMPTOBRANCHSTATE: return "JUMPTOBRANCHSTATE";
        case tracingStateMachine_StateId_CHECKSIZESTATE: return "CHECKSIZESTATE";
        case tracingStateMachine_StateId_FAILEDJUMPSTATE: return "FAILEDJUMPSTATE";
        case tracingStateMachine_StateId_GETCANDIDATESSTATE: return "GETCANDIDATESSTATE";
        case tracingStateMachine_StateId_JUMPTOTRIANGLESTATE: return "JUMPTOTRIANGLESTATE";
        case tracingStateMachine_StateId_FAIL: return "FAIL";
        case tracingStateMachine_StateId_FALLBACKPREPSTATE: return "FALLBACKPREPSTATE";
        case tracingStateMachine_StateId_LIFTEDPOSERANDOMTRAJSTATE: return "LIFTEDPOSERANDOMTRAJSTATE";
        case tracingStateMachine_StateId_LIFTEDPOSESTARIGHTLINESTATE: return "LIFTEDPOSESTARIGHTLINESTATE";
        case tracingStateMachine_StateId_MOVEWITHLIFTSTATE: return "MOVEWITHLIFTSTATE";
        case tracingStateMachine_StateId_TARGETPOSESTRAIGHTLINESTATE: return "TARGETPOSESTRAIGHTLINESTATE";
        case tracingStateMachine_StateId_TRIANGSETUPSTATE: return "TRIANGSETUPSTATE";
        case tracingStateMachine_StateId_SUCCESSFULJUMPSTATE: return "SUCCESSFULJUMPSTATE";
        case tracingStateMachine_StateId_LEASTNEIGHBOURSSEARCHSTATE: return "LEASTNEIGHBOURSSEARCHSTATE";
        case tracingStateMachine_StateId_REACHINGSTATE: return "REACHINGSTATE";
        case tracingStateMachine_StateId_GETCLOSESTSTATE: return "GETCLOSESTSTATE";
        case tracingStateMachine_StateId_GETPOSESTATEINREACHING: return "GETPOSESTATEINREACHING";
        case tracingStateMachine_StateId_MOVESTATEINREACHING: return "MOVESTATEINREACHING";
        case tracingStateMachine_StateId_REACHFAILED: return "REACHFAILED";
        case tracingStateMachine_StateId_TRACENEIGHBOURSTATE: return "TRACENEIGHBOURSTATE";
        case tracingStateMachine_StateId_FINISHTRANSBETWEENTRIANGLESSTATE: return "FINISHTRANSBETWEENTRIANGLESSTATE";
        case tracingStateMachine_StateId_MOVEFROMEDGESTATE: return "MOVEFROMEDGESTATE";
        case tracingStateMachine_StateId_MOVETOEDGESTATE: return "MOVETOEDGESTATE";
        case tracingStateMachine_StateId_POPHISTRORYANDMOVEBACKSTATE: return "POPHISTRORYANDMOVEBACKSTATE";
        case tracingStateMachine_StateId_ROTATEAROUNDEDGESTATE: return "ROTATEAROUNDEDGESTATE";
        case tracingStateMachine_StateId_UPDVALSONFAILSTATE: return "UPDVALSONFAILSTATE";
        default: return "?";
    }
}

// Thread safe.
char const * tracingStateMachine_event_id_to_string(tracingStateMachine_EventId id)
{
    switch (id)
    {
        case tracingStateMachine_EventId_DO: return "DO";
        default: return "?";
    }
}
