// Autogenerated with StateSmith 0.19.0+b5719011215d41a81572ed347c02b22db5d1a48f.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

// Whatever you put in this `FileTop` section will end up 
// being printed at the top of every generated code file.

#pragma once  // You can also specify normal include guard. See https://github.com/StateSmith/StateSmith/blob/main/docs/settings.md
#include <stdint.h>
#include <vector>
#include <stack>
#include <math.h>
#include <algorithm>
#include <thread>
#include <cmath>   
#include <trace_cube.hpp>

//=======NAMING UTILS========
using TriangleVec = std::vector<Triangle>;
using BoolVec = std::vector<bool>;
using Pose = geometry_msgs::msg::Pose;
using Tip = geometry_msgs::msg::Point;
using Quaternion - geometry_msgs::msg::Quaternion;
using std::size_t;
using Vec3d = double[3];
using Result = std::pair<std::vector<int>, std::vector<int>>;

enum class AttemptToReach{
   TRIANGLE_REACHED,
   TRIANGLE_FAILED,
   CENTER_TO_EDGE_FAILED,
   EDGE_TO_CENTER_FAILED,
   FAILED,
   EMPTY_VECTOR
};
enum class movementDirection{
   FORWARD,
   BACKWARDS
};
enum class waypointType{
   TRIANGLE,
   EDGE
};
//============================

//==ADD YOUT FUNCTIONS HERE==
AttemptToReach traceNeighbour();
void triangleExtraction();
int startOperation();
void init();
void goHome();
bool getTCPpose();
void getTCPorientation();
AttemptToReach attemptToReachNextClosest();
geometry_msgs::msg::Pose targetPose();
int getClosestTriangle();
float distanceToTCP();
bool moveToPoint(movementDirection movementDir = movementDirection::FORWARD, waypointType waypoint = waypointType::TRIANGLE, const std::vector<geometry_msgs::msg::Pose> &viaPoses = {});std::pair<std::vector<int>, std::vector<int>> triangleWithLeastNeighbours();
std::vector<Waypoint> extractOrderedPath();
float computeCoveragePercent();
bool confirmPathExecution();
bool executePlannedPath();
std::pair<std::vector<int>, std::vector<int>> triangleWithLeastNeighbours();//==============================

typedef enum tracingStateMachine_EventId
{
    tracingStateMachine_EventId_DO = 0 // The `do` event is special. State event handlers do not consume this event (ancestors all get it too) unless a transition occurs.
} tracingStateMachine_EventId;

enum
{
    tracingStateMachine_EventIdCount = 1
};

typedef enum tracingStateMachine_StateId
{
    tracingStateMachine_StateId_ROOT = 0,
    tracingStateMachine_StateId_ABORTSTATE = 1,
    tracingStateMachine_StateId_ATTEMPTNEXTCLOSESTSTATE = 2,
    tracingStateMachine_StateId_EXTRACTPATHSTATE = 3,
    tracingStateMachine_StateId_GETBRANCHSTATE = 4,
    tracingStateMachine_StateId_GETDISTANCESTATE = 5,
    tracingStateMachine_StateId_GETORIENTATIONSTATE = 6,
    tracingStateMachine_StateId_INITSTATE = 7,
    tracingStateMachine_StateId_JUMPTOBRANCHPOINTSTATE = 8,
    tracingStateMachine_StateId_JUMPTOBRANCHSTATE = 9,
    tracingStateMachine_StateId_JUMPTOTRIANGSTATE = 10,
    tracingStateMachine_StateId_LEASTNEIGHBOURSSEARCHSTATE = 11,
    tracingStateMachine_StateId_LIFTEDPOSESTATE = 12,
    tracingStateMachine_StateId_PLANOMPLSTATE = 13,
    tracingStateMachine_StateId_REACHINGSTATE = 14,
    tracingStateMachine_StateId_GETCLOSESTSTATE = 15,
    tracingStateMachine_StateId_GETPOSESTATEINREACHING = 16,
    tracingStateMachine_StateId_MOVESTATEINREACHING = 17,
    tracingStateMachine_StateId_REACHFAILED = 18,
    tracingStateMachine_StateId_REMEMBERPOINTSTATE = 19,
    tracingStateMachine_StateId_STATETOBUILD = 20,
    tracingStateMachine_StateId_TRACENEIGHBOURSTATE = 21,
    tracingStateMachine_StateId_FINISHTRANSBETWEENTRIANGLESSTATE = 22,
    tracingStateMachine_StateId_MOVEFROMEDGESTATE = 23,
    tracingStateMachine_StateId_MOVETOEDGESTATE = 24,
    tracingStateMachine_StateId_POPHISTRORYANDMOVEBACKSTATE = 25,
    tracingStateMachine_StateId_ROTATEAROUNDEDGESTATE = 26,
    tracingStateMachine_StateId_UPDVALSONFAILSTATE = 27,
    tracingStateMachine_StateId_TRIANGGLEEXTRACTIONSTATE = 28
} tracingStateMachine_StateId;

enum
{
    tracingStateMachine_StateIdCount = 29
};


// Generated state machine
// forward declaration
typedef struct tracingStateMachine tracingStateMachine;

// State machine variables. Can be used for inputs, outputs, user variables...
typedef struct tracingStateMachine_Vars
{
    TriangleVec vectorOfTriangles; 
        BoolVec traced; 
        Pose target_pose; 
    Pose oldPose;
        Triangle currentTriangle;
    Triangle previousTriangle;
    Edge egdeBetweenLastAndCurrent; 
        Triangle target; 
        AttemptToReach initialTriangle; 
        int chosenVector;
        int closestTriangle; 
        int iterator; 
        int operationSuccessCatcher; 
        size_t desiredVectorSize; 
        size_t size; 
    Tip edgePenTip;
    Quaternion quaternion;
        Vec3d currentTCP; 
        TriangleVec vectorOfDesiredTriangles; 
        TriangleVec singleNeighbourTriangles; 
        TriangleVec doubleNeighbourTriangles;
    AttemptToReach neighbourReachAttempt;Result result;
} tracingStateMachine_Vars;


// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void tracingStateMachine_ctor(tracingStateMachine* sm);

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void tracingStateMachine_start(tracingStateMachine* sm);

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void tracingStateMachine_dispatch_event(tracingStateMachine* sm, tracingStateMachine_EventId event_id);

// Thread safe.
char const * tracingStateMachine_state_id_to_string(tracingStateMachine_StateId id);

// Thread safe.
char const * tracingStateMachine_event_id_to_string(tracingStateMachine_EventId id);

// Generated state machine
struct tracingStateMachine
{
    // Used internally by state machine. Feel free to inspect, but don't modify.
    tracingStateMachine_StateId state_id;
    
    // Variables. Can be used for inputs, outputs, user variables...
    tracingStateMachine_Vars vars;
};

