// Autogenerated with StateSmith 0.19.0+b5719011215d41a81572ed347c02b22db5d1a48f.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

// Whatever you put in this `FileTop` section will end up 
// being printed at the top of every generated code file.

#include "tracingStateMachine.hpp"
#include <stdbool.h> // required for `consume_event` flag
#include <string.h> // for memset
    

// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(tracingStateMachine* sm, tracingStateMachine_StateId desired_state);

static void ROOT_enter(tracingStateMachine* sm);

static void ABORTSTATE_enter(tracingStateMachine* sm);

static void ABORTSTATE_exit(tracingStateMachine* sm);

static void ABORTSTATE_do(tracingStateMachine* sm);

static void ATTEMPTNEXTCLOSESTSTATE_enter(tracingStateMachine* sm);

static void ATTEMPTNEXTCLOSESTSTATE_exit(tracingStateMachine* sm);

static void ATTEMPTNEXTCLOSESTSTATE_do(tracingStateMachine* sm);

static void EXTRACTPATHSTATE_enter(tracingStateMachine* sm);

static void EXTRACTPATHSTATE_exit(tracingStateMachine* sm);

static void EXTRACTPATHSTATE_do(tracingStateMachine* sm);

static void GETBRANCHSTATE_enter(tracingStateMachine* sm);

static void GETBRANCHSTATE_exit(tracingStateMachine* sm);

static void GETBRANCHSTATE_do(tracingStateMachine* sm);

static void GETDISTANCESTATE_enter(tracingStateMachine* sm);

static void GETDISTANCESTATE_exit(tracingStateMachine* sm);

static void GETDISTANCESTATE_do(tracingStateMachine* sm);

static void GETORIENTATIONSTATE_enter(tracingStateMachine* sm);

static void GETORIENTATIONSTATE_exit(tracingStateMachine* sm);

static void GETORIENTATIONSTATE_do(tracingStateMachine* sm);

static void INITSTATE_enter(tracingStateMachine* sm);

static void INITSTATE_exit(tracingStateMachine* sm);

static void INITSTATE_do(tracingStateMachine* sm);

static void JUMPTOBRANCHPOINTSTATE_enter(tracingStateMachine* sm);

static void JUMPTOBRANCHPOINTSTATE_exit(tracingStateMachine* sm);

static void JUMPTOBRANCHPOINTSTATE_do(tracingStateMachine* sm);

static void JUMPTOBRANCHSTATE_enter(tracingStateMachine* sm);

static void JUMPTOBRANCHSTATE_exit(tracingStateMachine* sm);

static void JUMPTOBRANCHSTATE_do(tracingStateMachine* sm);

static void JUMPTOTRIANGSTATE_enter(tracingStateMachine* sm);

static void JUMPTOTRIANGSTATE_exit(tracingStateMachine* sm);

static void JUMPTOTRIANGSTATE_do(tracingStateMachine* sm);

static void LEASTNEIGHBOURSSEARCHSTATE_enter(tracingStateMachine* sm);

static void LEASTNEIGHBOURSSEARCHSTATE_exit(tracingStateMachine* sm);

static void LEASTNEIGHBOURSSEARCHSTATE_do(tracingStateMachine* sm);

static void LIFTEDPOSESTATE_enter(tracingStateMachine* sm);

static void LIFTEDPOSESTATE_exit(tracingStateMachine* sm);

static void LIFTEDPOSESTATE_do(tracingStateMachine* sm);

static void PLANOMPLSTATE_enter(tracingStateMachine* sm);

static void PLANOMPLSTATE_exit(tracingStateMachine* sm);

static void PLANOMPLSTATE_do(tracingStateMachine* sm);

static void REACHINGSTATE_enter(tracingStateMachine* sm);

static void REACHINGSTATE_exit(tracingStateMachine* sm);

static void GETCLOSESTSTATE_enter(tracingStateMachine* sm);

static void GETCLOSESTSTATE_exit(tracingStateMachine* sm);

static void GETCLOSESTSTATE_do(tracingStateMachine* sm);

static void GETPOSESTATEINREACHING_enter(tracingStateMachine* sm);

static void GETPOSESTATEINREACHING_exit(tracingStateMachine* sm);

static void GETPOSESTATEINREACHING_do(tracingStateMachine* sm);

static void MOVESTATEINREACHING_enter(tracingStateMachine* sm);

static void MOVESTATEINREACHING_exit(tracingStateMachine* sm);

static void MOVESTATEINREACHING_do(tracingStateMachine* sm);

static void REACHFAILED_enter(tracingStateMachine* sm);

static void REACHFAILED_exit(tracingStateMachine* sm);

static void REACHFAILED_do(tracingStateMachine* sm);

static void REMEMBERPOINTSTATE_enter(tracingStateMachine* sm);

static void REMEMBERPOINTSTATE_exit(tracingStateMachine* sm);

static void REMEMBERPOINTSTATE_do(tracingStateMachine* sm);

static void STATETOBUILD_enter(tracingStateMachine* sm);

static void STATETOBUILD_exit(tracingStateMachine* sm);

static void STATETOBUILD_do(tracingStateMachine* sm);

static void TRACENEIGHBOURSTATE_enter(tracingStateMachine* sm);

static void TRACENEIGHBOURSTATE_exit(tracingStateMachine* sm);

static void FINISHTRANSBETWEENTRIANGLESSTATE_enter(tracingStateMachine* sm);

static void FINISHTRANSBETWEENTRIANGLESSTATE_exit(tracingStateMachine* sm);

static void FINISHTRANSBETWEENTRIANGLESSTATE_do(tracingStateMachine* sm);

static void MOVEFROMEDGESTATE_enter(tracingStateMachine* sm);

static void MOVEFROMEDGESTATE_exit(tracingStateMachine* sm);

static void MOVEFROMEDGESTATE_do(tracingStateMachine* sm);

static void MOVETOEDGESTATE_enter(tracingStateMachine* sm);

static void MOVETOEDGESTATE_exit(tracingStateMachine* sm);

static void MOVETOEDGESTATE_do(tracingStateMachine* sm);

static void POPHISTRORYANDMOVEBACKSTATE_enter(tracingStateMachine* sm);

static void POPHISTRORYANDMOVEBACKSTATE_exit(tracingStateMachine* sm);

static void POPHISTRORYANDMOVEBACKSTATE_do(tracingStateMachine* sm);

static void ROTATEAROUNDEDGESTATE_enter(tracingStateMachine* sm);

static void ROTATEAROUNDEDGESTATE_exit(tracingStateMachine* sm);

static void ROTATEAROUNDEDGESTATE_do(tracingStateMachine* sm);

static void UPDVALSONFAILSTATE_enter(tracingStateMachine* sm);

static void UPDVALSONFAILSTATE_exit(tracingStateMachine* sm);

static void UPDVALSONFAILSTATE_do(tracingStateMachine* sm);

static void TRIANGGLEEXTRACTIONSTATE_enter(tracingStateMachine* sm);

static void TRIANGGLEEXTRACTIONSTATE_exit(tracingStateMachine* sm);

static void TRIANGGLEEXTRACTIONSTATE_do(tracingStateMachine* sm);


// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void tracingStateMachine_ctor(tracingStateMachine* sm)
{
    memset(sm, 0, sizeof(*sm));
}

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void tracingStateMachine_start(tracingStateMachine* sm)
{
    ROOT_enter(sm);
    // ROOT behavior
    // uml: TransitionTo(ROOT.<InitialState>)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
        // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.
        
        // ROOT.<InitialState> behavior
        // uml: TransitionTo(initState)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: ``.
            
            // Step 3: Enter/move towards transition target `initState`.
            INITSTATE_enter(sm);
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for ROOT.<InitialState>
    } // end of behavior for ROOT
}

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void tracingStateMachine_dispatch_event(tracingStateMachine* sm, tracingStateMachine_EventId event_id)
{
    // This state machine design only has a single event type so we can safely assume
    // that the dispatched event is `do` without checking the `event_id` parameter.
    (void)event_id; // This line prevents an 'unused variable' compiler warning
    
    switch (sm->state_id)
    {
        // STATE: tracingStateMachine
        case tracingStateMachine_StateId_ROOT:
            // state and ancestors have no handler for `do` event.
            break;
        
        // STATE: abortState
        case tracingStateMachine_StateId_ABORTSTATE:
            ABORTSTATE_do(sm); 
            break;
        
        // STATE: attemptNextClosestState
        case tracingStateMachine_StateId_ATTEMPTNEXTCLOSESTSTATE:
            ATTEMPTNEXTCLOSESTSTATE_do(sm); 
            break;
        
        // STATE: extractPathState
        case tracingStateMachine_StateId_EXTRACTPATHSTATE:
            EXTRACTPATHSTATE_do(sm); 
            break;
        
        // STATE: getBranchState
        case tracingStateMachine_StateId_GETBRANCHSTATE:
            GETBRANCHSTATE_do(sm); 
            break;
        
        // STATE: getDistanceState
        case tracingStateMachine_StateId_GETDISTANCESTATE:
            GETDISTANCESTATE_do(sm); 
            break;
        
        // STATE: getOrientationState
        case tracingStateMachine_StateId_GETORIENTATIONSTATE:
            GETORIENTATIONSTATE_do(sm); 
            break;
        
        // STATE: initState
        case tracingStateMachine_StateId_INITSTATE:
            INITSTATE_do(sm); 
            break;
        
        // STATE: jumpToBranchPointState
        case tracingStateMachine_StateId_JUMPTOBRANCHPOINTSTATE:
            JUMPTOBRANCHPOINTSTATE_do(sm); 
            break;
        
        // STATE: jumpToBranchState
        case tracingStateMachine_StateId_JUMPTOBRANCHSTATE:
            JUMPTOBRANCHSTATE_do(sm); 
            break;
        
        // STATE: jumpToTriangState
        case tracingStateMachine_StateId_JUMPTOTRIANGSTATE:
            JUMPTOTRIANGSTATE_do(sm); 
            break;
        
        // STATE: leastNeighboursSearchState
        case tracingStateMachine_StateId_LEASTNEIGHBOURSSEARCHSTATE:
            LEASTNEIGHBOURSSEARCHSTATE_do(sm); 
            break;
        
        // STATE: liftedPoseState
        case tracingStateMachine_StateId_LIFTEDPOSESTATE:
            LIFTEDPOSESTATE_do(sm); 
            break;
        
        // STATE: planOMPLState
        case tracingStateMachine_StateId_PLANOMPLSTATE:
            PLANOMPLSTATE_do(sm); 
            break;
        
        // STATE: reachingState
        case tracingStateMachine_StateId_REACHINGSTATE:
            // state and ancestors have no handler for `do` event.
            break;
        
        // STATE: getClosestState
        case tracingStateMachine_StateId_GETCLOSESTSTATE:
            GETCLOSESTSTATE_do(sm); 
            break;
        
        // STATE: getPoseStateInReaching
        case tracingStateMachine_StateId_GETPOSESTATEINREACHING:
            GETPOSESTATEINREACHING_do(sm); 
            break;
        
        // STATE: moveStateInReaching
        case tracingStateMachine_StateId_MOVESTATEINREACHING:
            MOVESTATEINREACHING_do(sm); 
            break;
        
        // STATE: reachFailed
        case tracingStateMachine_StateId_REACHFAILED:
            REACHFAILED_do(sm); 
            break;
        
        // STATE: rememberPointState
        case tracingStateMachine_StateId_REMEMBERPOINTSTATE:
            REMEMBERPOINTSTATE_do(sm); 
            break;
        
        // STATE: StateToBuild
        case tracingStateMachine_StateId_STATETOBUILD:
            STATETOBUILD_do(sm); 
            break;
        
        // STATE: traceNeighbourState
        case tracingStateMachine_StateId_TRACENEIGHBOURSTATE:
            // state and ancestors have no handler for `do` event.
            break;
        
        // STATE: finishTransBetweenTrianglesState
        case tracingStateMachine_StateId_FINISHTRANSBETWEENTRIANGLESSTATE:
            FINISHTRANSBETWEENTRIANGLESSTATE_do(sm); 
            break;
        
        // STATE: moveFromEdgeState
        case tracingStateMachine_StateId_MOVEFROMEDGESTATE:
            MOVEFROMEDGESTATE_do(sm); 
            break;
        
        // STATE: moveToEdgeState
        case tracingStateMachine_StateId_MOVETOEDGESTATE:
            MOVETOEDGESTATE_do(sm); 
            break;
        
        // STATE: popHistroryAndMoveBackState
        case tracingStateMachine_StateId_POPHISTRORYANDMOVEBACKSTATE:
            POPHISTRORYANDMOVEBACKSTATE_do(sm); 
            break;
        
        // STATE: rotateAroundEdgeState
        case tracingStateMachine_StateId_ROTATEAROUNDEDGESTATE:
            ROTATEAROUNDEDGESTATE_do(sm); 
            break;
        
        // STATE: updValsOnFailState
        case tracingStateMachine_StateId_UPDVALSONFAILSTATE:
            UPDVALSONFAILSTATE_do(sm); 
            break;
        
        // STATE: trianggleExtractionState
        case tracingStateMachine_StateId_TRIANGGLEEXTRACTIONSTATE:
            TRIANGGLEEXTRACTIONSTATE_do(sm); 
            break;
    }
    
}

// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(tracingStateMachine* sm, tracingStateMachine_StateId desired_state)
{
    while (sm->state_id != desired_state)
    {
        switch (sm->state_id)
        {
            case tracingStateMachine_StateId_ABORTSTATE: ABORTSTATE_exit(sm); break;
            
            case tracingStateMachine_StateId_ATTEMPTNEXTCLOSESTSTATE: ATTEMPTNEXTCLOSESTSTATE_exit(sm); break;
            
            case tracingStateMachine_StateId_EXTRACTPATHSTATE: EXTRACTPATHSTATE_exit(sm); break;
            
            case tracingStateMachine_StateId_GETBRANCHSTATE: GETBRANCHSTATE_exit(sm); break;
            
            case tracingStateMachine_StateId_GETDISTANCESTATE: GETDISTANCESTATE_exit(sm); break;
            
            case tracingStateMachine_StateId_GETORIENTATIONSTATE: GETORIENTATIONSTATE_exit(sm); break;
            
            case tracingStateMachine_StateId_INITSTATE: INITSTATE_exit(sm); break;
            
            case tracingStateMachine_StateId_JUMPTOBRANCHPOINTSTATE: JUMPTOBRANCHPOINTSTATE_exit(sm); break;
            
            case tracingStateMachine_StateId_JUMPTOBRANCHSTATE: JUMPTOBRANCHSTATE_exit(sm); break;
            
            case tracingStateMachine_StateId_JUMPTOTRIANGSTATE: JUMPTOTRIANGSTATE_exit(sm); break;
            
            case tracingStateMachine_StateId_LEASTNEIGHBOURSSEARCHSTATE: LEASTNEIGHBOURSSEARCHSTATE_exit(sm); break;
            
            case tracingStateMachine_StateId_LIFTEDPOSESTATE: LIFTEDPOSESTATE_exit(sm); break;
            
            case tracingStateMachine_StateId_PLANOMPLSTATE: PLANOMPLSTATE_exit(sm); break;
            
            case tracingStateMachine_StateId_REACHINGSTATE: REACHINGSTATE_exit(sm); break;
            
            case tracingStateMachine_StateId_GETCLOSESTSTATE: GETCLOSESTSTATE_exit(sm); break;
            
            case tracingStateMachine_StateId_GETPOSESTATEINREACHING: GETPOSESTATEINREACHING_exit(sm); break;
            
            case tracingStateMachine_StateId_MOVESTATEINREACHING: MOVESTATEINREACHING_exit(sm); break;
            
            case tracingStateMachine_StateId_REACHFAILED: REACHFAILED_exit(sm); break;
            
            case tracingStateMachine_StateId_REMEMBERPOINTSTATE: REMEMBERPOINTSTATE_exit(sm); break;
            
            case tracingStateMachine_StateId_STATETOBUILD: STATETOBUILD_exit(sm); break;
            
            case tracingStateMachine_StateId_TRACENEIGHBOURSTATE: TRACENEIGHBOURSTATE_exit(sm); break;
            
            case tracingStateMachine_StateId_FINISHTRANSBETWEENTRIANGLESSTATE: FINISHTRANSBETWEENTRIANGLESSTATE_exit(sm); break;
            
            case tracingStateMachine_StateId_MOVEFROMEDGESTATE: MOVEFROMEDGESTATE_exit(sm); break;
            
            case tracingStateMachine_StateId_MOVETOEDGESTATE: MOVETOEDGESTATE_exit(sm); break;
            
            case tracingStateMachine_StateId_POPHISTRORYANDMOVEBACKSTATE: POPHISTRORYANDMOVEBACKSTATE_exit(sm); break;
            
            case tracingStateMachine_StateId_ROTATEAROUNDEDGESTATE: ROTATEAROUNDEDGESTATE_exit(sm); break;
            
            case tracingStateMachine_StateId_UPDVALSONFAILSTATE: UPDVALSONFAILSTATE_exit(sm); break;
            
            case tracingStateMachine_StateId_TRIANGGLEEXTRACTIONSTATE: TRIANGGLEEXTRACTIONSTATE_exit(sm); break;
            
            default: return;  // Just to be safe. Prevents infinite loop if state ID memory is somehow corrupted.
        }
    }
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state ROOT
////////////////////////////////////////////////////////////////////////////////

static void ROOT_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_ROOT;
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state ABORTSTATE
////////////////////////////////////////////////////////////////////////////////

static void ABORTSTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_ABORTSTATE;
    
    // abortState behavior
    // uml: enter
    {
        // Step 1: execute action ``
    } // end of behavior for abortState
}

static void ABORTSTATE_exit(tracingStateMachine* sm)
{
    // abortState behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for abortState
    
    sm->state_id = tracingStateMachine_StateId_ROOT;
}

static void ABORTSTATE_do(tracingStateMachine* sm)
{
    // abortState behavior
    // uml: do / { abort(); }
    {
        // Step 1: execute action `abort();`
        abort();
    } // end of behavior for abortState
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state ATTEMPTNEXTCLOSESTSTATE
////////////////////////////////////////////////////////////////////////////////

static void ATTEMPTNEXTCLOSESTSTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_ATTEMPTNEXTCLOSESTSTATE;
    
    // attemptNextClosestState behavior
    // uml: enter / { chosenVector++; }
    {
        // Step 1: execute action `chosenVector++;`
        sm->vars.chosenVector++;
    } // end of behavior for attemptNextClosestState
}

static void ATTEMPTNEXTCLOSESTSTATE_exit(tracingStateMachine* sm)
{
    // attemptNextClosestState behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for attemptNextClosestState
    
    sm->state_id = tracingStateMachine_StateId_ROOT;
}

static void ATTEMPTNEXTCLOSESTSTATE_do(tracingStateMachine* sm)
{
    // attemptNextClosestState behavior
    // uml: do / { attemptToReachNextClosest(); }
    {
        // Step 1: execute action `attemptToReachNextClosest();`
        attemptToReachNextClosest();
    } // end of behavior for attemptNextClosestState
    
    // attemptNextClosestState behavior
    // uml: do [chosenVector > = 3\n&& initialTriangle != AttemptToReach::TRIANGLE_REACHED] TransitionTo(abortState)
    if (sm->vars.chosenVector > = 3&& sm->vars.initialTriangle != AttemptToReach::TRIANGLE_REACHED)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        ATTEMPTNEXTCLOSESTSTATE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `abortState`.
        ABORTSTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for attemptNextClosestState
    
    // attemptNextClosestState behavior
    // uml: do [operationSuccessCatcher] TransitionTo(leastNeighboursSearchState)
    if (sm->vars.operationSuccessCatcher)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        ATTEMPTNEXTCLOSESTSTATE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `leastNeighboursSearchState`.
        LEASTNEIGHBOURSSEARCHSTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for attemptNextClosestState
    
    // attemptNextClosestState behavior
    // uml: do [!operationResultCatcher] TransitionTo(getPoseStateInReaching)
    if (!operationResultCatcher)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        ATTEMPTNEXTCLOSESTSTATE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `getPoseStateInReaching`.
        REACHINGSTATE_enter(sm);
        GETPOSESTATEINREACHING_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for attemptNextClosestState
    
    // attemptNextClosestState behavior
    // uml: else do TransitionTo(attemptNextClosestState)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        ATTEMPTNEXTCLOSESTSTATE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `attemptNextClosestState`.
        ATTEMPTNEXTCLOSESTSTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for attemptNextClosestState
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state EXTRACTPATHSTATE
////////////////////////////////////////////////////////////////////////////////

static void EXTRACTPATHSTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_EXTRACTPATHSTATE;
    
    // extractPathState behavior
    // uml: enter
    {
        // Step 1: execute action ``
    } // end of behavior for extractPathState
}

static void EXTRACTPATHSTATE_exit(tracingStateMachine* sm)
{
    // extractPathState behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for extractPathState
    
    sm->state_id = tracingStateMachine_StateId_ROOT;
}

static void EXTRACTPATHSTATE_do(tracingStateMachine* sm)
{
    // extractPathState behavior
    // uml: do / { extractOrderedPath(); }
    {
        // Step 1: execute action `extractOrderedPath();`
        extractOrderedPath();
    } // end of behavior for extractPathState
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state GETBRANCHSTATE
////////////////////////////////////////////////////////////////////////////////

static void GETBRANCHSTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_GETBRANCHSTATE;
    
    // getBranchState behavior
    // uml: enter
    {
        // Step 1: execute action ``
    } // end of behavior for getBranchState
}

static void GETBRANCHSTATE_exit(tracingStateMachine* sm)
{
    // getBranchState behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for getBranchState
    
    sm->state_id = tracingStateMachine_StateId_ROOT;
}

static void GETBRANCHSTATE_do(tracingStateMachine* sm)
{
    // getBranchState behavior
    // uml: do / { getBranchCandidates(); }
    {
        // Step 1: execute action `getBranchCandidates();`
        getBranchCandidates();
    } // end of behavior for getBranchState
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state GETDISTANCESTATE
////////////////////////////////////////////////////////////////////////////////

static void GETDISTANCESTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_GETDISTANCESTATE;
    
    // getDistanceState behavior
    // uml: enter
    {
        // Step 1: execute action ``
    } // end of behavior for getDistanceState
}

static void GETDISTANCESTATE_exit(tracingStateMachine* sm)
{
    // getDistanceState behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for getDistanceState
    
    sm->state_id = tracingStateMachine_StateId_ROOT;
}

static void GETDISTANCESTATE_do(tracingStateMachine* sm)
{
    // getDistanceState behavior
    // uml: do / { distanceToTCP(); }
    {
        // Step 1: execute action `distanceToTCP();`
        distanceToTCP();
    } // end of behavior for getDistanceState
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state GETORIENTATIONSTATE
////////////////////////////////////////////////////////////////////////////////

static void GETORIENTATIONSTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_GETORIENTATIONSTATE;
    
    // getOrientationState behavior
    // uml: enter
    {
        // Step 1: execute action ``
    } // end of behavior for getOrientationState
}

static void GETORIENTATIONSTATE_exit(tracingStateMachine* sm)
{
    // getOrientationState behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for getOrientationState
    
    sm->state_id = tracingStateMachine_StateId_ROOT;
}

static void GETORIENTATIONSTATE_do(tracingStateMachine* sm)
{
    // getOrientationState behavior
    // uml: do / { getTCPorientation(); }
    {
        // Step 1: execute action `getTCPorientation();`
        getTCPorientation();
    } // end of behavior for getOrientationState
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state INITSTATE
////////////////////////////////////////////////////////////////////////////////

static void INITSTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_INITSTATE;
    
    // initState behavior
    // uml: enter / { iterator = 0; }
    {
        // Step 1: execute action `iterator = 0;`
        sm->vars.iterator = 0;
    } // end of behavior for initState
}

static void INITSTATE_exit(tracingStateMachine* sm)
{
    // initState behavior
    // uml: exit / { chosenVector = -1; }
    {
        // Step 1: execute action `chosenVector = -1;`
        sm->vars.chosenVector = -1;
    } // end of behavior for initState
    
    sm->state_id = tracingStateMachine_StateId_ROOT;
}

static void INITSTATE_do(tracingStateMachine* sm)
{
    // initState behavior
    // uml: do / { initialTriangle = AttemptToReach::EMPTY_VECTOR; }
    {
        // Step 1: execute action `initialTriangle = AttemptToReach::EMPTY_VECTOR;`
        sm->vars.initialTriangle = AttemptToReach::EMPTY_VECTOR;
    } // end of behavior for initState
    
    // initState behavior
    // uml: do TransitionTo(attemptNextClosestState)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        INITSTATE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `attemptNextClosestState`.
        ATTEMPTNEXTCLOSESTSTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for initState
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state JUMPTOBRANCHPOINTSTATE
////////////////////////////////////////////////////////////////////////////////

static void JUMPTOBRANCHPOINTSTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_JUMPTOBRANCHPOINTSTATE;
    
    // jumpToBranchPointState behavior
    // uml: enter
    {
        // Step 1: execute action ``
    } // end of behavior for jumpToBranchPointState
}

static void JUMPTOBRANCHPOINTSTATE_exit(tracingStateMachine* sm)
{
    // jumpToBranchPointState behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for jumpToBranchPointState
    
    sm->state_id = tracingStateMachine_StateId_ROOT;
}

static void JUMPTOBRANCHPOINTSTATE_do(tracingStateMachine* sm)
{
    // jumpToBranchPointState behavior
    // uml: do / { jumpToNearestBranchPoint(); }
    {
        // Step 1: execute action `jumpToNearestBranchPoint();`
        jumpToNearestBranchPoint();
    } // end of behavior for jumpToBranchPointState
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state JUMPTOBRANCHSTATE
////////////////////////////////////////////////////////////////////////////////

static void JUMPTOBRANCHSTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_JUMPTOBRANCHSTATE;
    
    // jumpToBranchState behavior
    // uml: enter
    {
        // Step 1: execute action ``
    } // end of behavior for jumpToBranchState
}

static void JUMPTOBRANCHSTATE_exit(tracingStateMachine* sm)
{
    // jumpToBranchState behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for jumpToBranchState
    
    sm->state_id = tracingStateMachine_StateId_ROOT;
}

static void JUMPTOBRANCHSTATE_do(tracingStateMachine* sm)
{
    // jumpToBranchState behavior
    // uml: do / { operationSuccessCatcher = jumpToNearestPoint(); }
    {
        // Step 1: execute action `operationSuccessCatcher = jumpToNearestPoint();`
        sm->vars.operationSuccessCatcher = jumpToNearestPoint();
    } // end of behavior for jumpToBranchState
    
    // jumpToBranchState behavior
    // uml: do TransitionTo(StateToBuild)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        JUMPTOBRANCHSTATE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `StateToBuild`.
        STATETOBUILD_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for jumpToBranchState
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state JUMPTOTRIANGSTATE
////////////////////////////////////////////////////////////////////////////////

static void JUMPTOTRIANGSTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_JUMPTOTRIANGSTATE;
    
    // jumpToTriangState behavior
    // uml: enter
    {
        // Step 1: execute action ``
    } // end of behavior for jumpToTriangState
}

static void JUMPTOTRIANGSTATE_exit(tracingStateMachine* sm)
{
    // jumpToTriangState behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for jumpToTriangState
    
    sm->state_id = tracingStateMachine_StateId_ROOT;
}

static void JUMPTOTRIANGSTATE_do(tracingStateMachine* sm)
{
    // jumpToTriangState behavior
    // uml: do / { jumpToTriangle(); }
    {
        // Step 1: execute action `jumpToTriangle();`
        jumpToTriangle();
    } // end of behavior for jumpToTriangState
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state LEASTNEIGHBOURSSEARCHSTATE
////////////////////////////////////////////////////////////////////////////////

static void LEASTNEIGHBOURSSEARCHSTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_LEASTNEIGHBOURSSEARCHSTATE;
    
    // leastNeighboursSearchState behavior
    // uml: enter / { if(pathHistory.empty() && stackOfReachableWaypoints.empty())\nbranchPoints.clear(); }
    {
        // Step 1: execute action `if(pathHistory.empty() && stackOfReachableWaypoints.empty())\nbranchPoints.clear();`
        if(pathHistory.empty() && stackOfReachableWaypoints.empty())
        branchPoints.clear();
    } // end of behavior for leastNeighboursSearchState
}

static void LEASTNEIGHBOURSSEARCHSTATE_exit(tracingStateMachine* sm)
{
    // leastNeighboursSearchState behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for leastNeighboursSearchState
    
    sm->state_id = tracingStateMachine_StateId_ROOT;
}

static void LEASTNEIGHBOURSSEARCHSTATE_do(tracingStateMachine* sm)
{
    // leastNeighboursSearchState behavior
    // uml: do / { result = triangleWithLeastNeighbours(); }
    {
        // Step 1: execute action `result = triangleWithLeastNeighbours();`
        sm->vars.result = triangleWithLeastNeighbours();
    } // end of behavior for leastNeighboursSearchState
    
    // leastNeighboursSearchState behavior
    // uml: do [!result.first.empty() &&\n!result.second.empty() &&] TransitionTo(moveToEdgeState)
    if (!sm->vars.result.first.empty() &&!sm->vars.result.second.empty() &&)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        LEASTNEIGHBOURSSEARCHSTATE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `moveToEdgeState`.
        TRACENEIGHBOURSTATE_enter(sm);
        MOVETOEDGESTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for leastNeighboursSearchState
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state LIFTEDPOSESTATE
////////////////////////////////////////////////////////////////////////////////

static void LIFTEDPOSESTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_LIFTEDPOSESTATE;
    
    // liftedPoseState behavior
    // uml: enter
    {
        // Step 1: execute action ``
    } // end of behavior for liftedPoseState
}

static void LIFTEDPOSESTATE_exit(tracingStateMachine* sm)
{
    // liftedPoseState behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for liftedPoseState
    
    sm->state_id = tracingStateMachine_StateId_ROOT;
}

static void LIFTEDPOSESTATE_do(tracingStateMachine* sm)
{
    // liftedPoseState behavior
    // uml: do / { liftedPose(); }
    {
        // Step 1: execute action `liftedPose();`
        liftedPose();
    } // end of behavior for liftedPoseState
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state PLANOMPLSTATE
////////////////////////////////////////////////////////////////////////////////

static void PLANOMPLSTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_PLANOMPLSTATE;
    
    // planOMPLState behavior
    // uml: enter
    {
        // Step 1: execute action ``
    } // end of behavior for planOMPLState
}

static void PLANOMPLSTATE_exit(tracingStateMachine* sm)
{
    // planOMPLState behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for planOMPLState
    
    sm->state_id = tracingStateMachine_StateId_ROOT;
}

static void PLANOMPLSTATE_do(tracingStateMachine* sm)
{
    // planOMPLState behavior
    // uml: do / { planOMPLPose(); }
    {
        // Step 1: execute action `planOMPLPose();`
        planOMPLPose();
    } // end of behavior for planOMPLState
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state REACHINGSTATE
////////////////////////////////////////////////////////////////////////////////

static void REACHINGSTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_REACHINGSTATE;
}

static void REACHINGSTATE_exit(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_ROOT;
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state GETCLOSESTSTATE
////////////////////////////////////////////////////////////////////////////////

static void GETCLOSESTSTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_GETCLOSESTSTATE;
    
    // getClosestState behavior
    // uml: enter
    {
        // Step 1: execute action ``
    } // end of behavior for getClosestState
}

static void GETCLOSESTSTATE_exit(tracingStateMachine* sm)
{
    // getClosestState behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for getClosestState
    
    sm->state_id = tracingStateMachine_StateId_REACHINGSTATE;
}

static void GETCLOSESTSTATE_do(tracingStateMachine* sm)
{
    // getClosestState behavior
    // uml: do / { closestTriangle = getClosestTriangle();\ntarget = vectorOfDesiredTriangles[closestTriangle] }
    {
        // Step 1: execute action `closestTriangle = getClosestTriangle();\ntarget = vectorOfDesiredTriangles[closestTriangle]`
        sm->vars.closestTriangle = getClosestTriangle();
        sm->vars.target = sm->vars.vectorOfDesiredTriangles[sm->vars.closestTriangle]
    } // end of behavior for getClosestState
    
    // getClosestState behavior
    // uml: do TransitionTo(moveStateInReaching)
    {
        // Step 1: Exit states until we reach `reachingState` state (Least Common Ancestor for transition).
        GETCLOSESTSTATE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `moveStateInReaching`.
        MOVESTATEINREACHING_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for getClosestState
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state GETPOSESTATEINREACHING
////////////////////////////////////////////////////////////////////////////////

static void GETPOSESTATEINREACHING_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_GETPOSESTATEINREACHING;
    
    // getPoseStateInReaching behavior
    // uml: enter
    {
        // Step 1: execute action ``
    } // end of behavior for getPoseStateInReaching
}

static void GETPOSESTATEINREACHING_exit(tracingStateMachine* sm)
{
    // getPoseStateInReaching behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for getPoseStateInReaching
    
    sm->state_id = tracingStateMachine_StateId_REACHINGSTATE;
}

static void GETPOSESTATEINREACHING_do(tracingStateMachine* sm)
{
    // getPoseStateInReaching behavior
    // uml: do / { operationSuccessCatcher = getTCPpose(); }
    {
        // Step 1: execute action `operationSuccessCatcher = getTCPpose();`
        sm->vars.operationSuccessCatcher = getTCPpose();
    } // end of behavior for getPoseStateInReaching
    
    // getPoseStateInReaching behavior
    // uml: do [operationSuccessCatcher] TransitionTo(getClosestState)
    if (sm->vars.operationSuccessCatcher)
    {
        // Step 1: Exit states until we reach `reachingState` state (Least Common Ancestor for transition).
        GETPOSESTATEINREACHING_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `getClosestState`.
        GETCLOSESTSTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for getPoseStateInReaching
    
    // getPoseStateInReaching behavior
    // uml: do [!operationSuccessCatcher] TransitionTo(abortState)
    if (!sm->vars.operationSuccessCatcher)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, tracingStateMachine_StateId_ROOT);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `abortState`.
        ABORTSTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for getPoseStateInReaching
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state MOVESTATEINREACHING
////////////////////////////////////////////////////////////////////////////////

static void MOVESTATEINREACHING_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_MOVESTATEINREACHING;
    
    // moveStateInReaching behavior
    // uml: enter
    {
        // Step 1: execute action ``
    } // end of behavior for moveStateInReaching
}

static void MOVESTATEINREACHING_exit(tracingStateMachine* sm)
{
    // moveStateInReaching behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for moveStateInReaching
    
    sm->state_id = tracingStateMachine_StateId_REACHINGSTATE;
}

static void MOVESTATEINREACHING_do(tracingStateMachine* sm)
{
    // moveStateInReaching behavior
    // uml: do / { targetPose();\noperationSuccessCatcher  = moveToPoint();\niterator++; }
    {
        // Step 1: execute action `targetPose();\noperationSuccessCatcher  = moveToPoint();\niterator++;`
        targetPose();
        sm->vars.operationSuccessCatcher  = moveToPoint();
        sm->vars.iterator++;
    } // end of behavior for moveStateInReaching
    
    // moveStateInReaching behavior
    // uml: do [!operationSuccessCatcher] TransitionTo(reachFailed)
    if (!sm->vars.operationSuccessCatcher)
    {
        // Step 1: Exit states until we reach `reachingState` state (Least Common Ancestor for transition).
        MOVESTATEINREACHING_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `reachFailed`.
        REACHFAILED_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for moveStateInReaching
    
    // moveStateInReaching behavior
    // uml: do [operationSuccessCatcher] TransitionTo(attemptNextClosestState)
    if (sm->vars.operationSuccessCatcher)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, tracingStateMachine_StateId_ROOT);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `attemptNextClosestState`.
        ATTEMPTNEXTCLOSESTSTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for moveStateInReaching
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state REACHFAILED
////////////////////////////////////////////////////////////////////////////////

static void REACHFAILED_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_REACHFAILED;
    
    // reachFailed behavior
    // uml: enter
    {
        // Step 1: execute action ``
    } // end of behavior for reachFailed
}

static void REACHFAILED_exit(tracingStateMachine* sm)
{
    // reachFailed behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for reachFailed
    
    sm->state_id = tracingStateMachine_StateId_REACHINGSTATE;
}

static void REACHFAILED_do(tracingStateMachine* sm)
{
    // reachFailed behavior
    // uml: do / { vectorOfDesiredTriangles[closestTriangle].unreachableCounter++;\nvectorOfDesiredTriangles.erase(vectorOfDesiredTriangles.begin() + closestTriangle); }
    {
        // Step 1: execute action `vectorOfDesiredTriangles[closestTriangle].unreachableCounter++;\nvectorOfDesiredTriangles.erase(vectorOfDesiredTriangles.begin() + closestTriangle);`
        sm->vars.vectorOfDesiredTriangles[sm->vars.closestTriangle].unreachableCounter++;
        sm->vars.vectorOfDesiredTriangles.erase(sm->vars.vectorOfDesiredTriangles.begin() + sm->vars.closestTriangle);
    } // end of behavior for reachFailed
    
    // reachFailed behavior
    // uml: do [iterator < \ndesiredVectorSize] TransitionTo(getClosestState)
    if (sm->vars.iterator < sm->vars.desiredVectorSize)
    {
        // Step 1: Exit states until we reach `reachingState` state (Least Common Ancestor for transition).
        REACHFAILED_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `getClosestState`.
        GETCLOSESTSTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for reachFailed
    
    // reachFailed behavior
    // uml: else do TransitionTo(attemptNextClosestState)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, tracingStateMachine_StateId_ROOT);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `attemptNextClosestState`.
        ATTEMPTNEXTCLOSESTSTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for reachFailed
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state REMEMBERPOINTSTATE
////////////////////////////////////////////////////////////////////////////////

static void REMEMBERPOINTSTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_REMEMBERPOINTSTATE;
    
    // rememberPointState behavior
    // uml: enter
    {
        // Step 1: execute action ``
    } // end of behavior for rememberPointState
}

static void REMEMBERPOINTSTATE_exit(tracingStateMachine* sm)
{
    // rememberPointState behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for rememberPointState
    
    sm->state_id = tracingStateMachine_StateId_ROOT;
}

static void REMEMBERPOINTSTATE_do(tracingStateMachine* sm)
{
    // rememberPointState behavior
    // uml: do / { rememberBranchPoint(); }
    {
        // Step 1: execute action `rememberBranchPoint();`
        rememberBranchPoint();
    } // end of behavior for rememberPointState
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state STATETOBUILD
////////////////////////////////////////////////////////////////////////////////

static void STATETOBUILD_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_STATETOBUILD;
    
    // StateToBuild behavior
    // uml: enter
    {
        // Step 1: execute action ``
    } // end of behavior for StateToBuild
}

static void STATETOBUILD_exit(tracingStateMachine* sm)
{
    // StateToBuild behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for StateToBuild
    
    sm->state_id = tracingStateMachine_StateId_ROOT;
}

static void STATETOBUILD_do(tracingStateMachine* sm)
{
    // StateToBuild behavior
    // uml: do / { //this state is only used to make\n//sure the sm so far is compilable }
    {
        // Step 1: execute action `//this state is only used to make\n//sure the sm so far is compilable`
        //this state is only used to make
        //sure the sm so far is compilable<EOF>
    } // end of behavior for StateToBuild
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state TRACENEIGHBOURSTATE
////////////////////////////////////////////////////////////////////////////////

static void TRACENEIGHBOURSTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_TRACENEIGHBOURSTATE;
}

static void TRACENEIGHBOURSTATE_exit(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_ROOT;
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state FINISHTRANSBETWEENTRIANGLESSTATE
////////////////////////////////////////////////////////////////////////////////

static void FINISHTRANSBETWEENTRIANGLESSTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_FINISHTRANSBETWEENTRIANGLESSTATE;
    
    // finishTransBetweenTrianglesState behavior
    // uml: enter
    {
        // Step 1: execute action ``
    } // end of behavior for finishTransBetweenTrianglesState
}

static void FINISHTRANSBETWEENTRIANGLESSTATE_exit(tracingStateMachine* sm)
{
    // finishTransBetweenTrianglesState behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for finishTransBetweenTrianglesState
    
    sm->state_id = tracingStateMachine_StateId_TRACENEIGHBOURSTATE;
}

static void FINISHTRANSBETWEENTRIANGLESSTATE_do(tracingStateMachine* sm)
{
    // finishTransBetweenTrianglesState behavior
    // uml: do / { currentTriangle.traced = true;\ntraced[currentTriangle.myIndex] = true;\ncurrentTriangle = result.first[iterator];\niterator = 0;\nrememberBranchPoint(); }
    {
        // Step 1: execute action `currentTriangle.traced = true;\ntraced[currentTriangle.myIndex] = true;\ncurrentTriangle = result.first[iterator];\niterator = 0;\nrememberBranchPoint();`
        sm->vars.currentTriangle.traced = true;
        sm->vars.traced[sm->vars.currentTriangle.myIndex] = true;
        sm->vars.currentTriangle = sm->vars.result.first[sm->vars.iterator];
        sm->vars.iterator = 0;
        rememberBranchPoint();
    } // end of behavior for finishTransBetweenTrianglesState
    
    // finishTransBetweenTrianglesState behavior
    // uml: do TransitionTo(StateToBuild)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, tracingStateMachine_StateId_ROOT);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `StateToBuild`.
        STATETOBUILD_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for finishTransBetweenTrianglesState
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state MOVEFROMEDGESTATE
////////////////////////////////////////////////////////////////////////////////

static void MOVEFROMEDGESTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_MOVEFROMEDGESTATE;
    
    // moveFromEdgeState behavior
    // uml: enter / { targetPose(currentTriangle); }
    {
        // Step 1: execute action `targetPose(currentTriangle);`
        targetPose(sm->vars.currentTriangle);
    } // end of behavior for moveFromEdgeState
}

static void MOVEFROMEDGESTATE_exit(tracingStateMachine* sm)
{
    // moveFromEdgeState behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for moveFromEdgeState
    
    sm->state_id = tracingStateMachine_StateId_TRACENEIGHBOURSTATE;
}

static void MOVEFROMEDGESTATE_do(tracingStateMachine* sm)
{
    // moveFromEdgeState behavior
    // uml: do / { operationSuccessCatcher = moveToPoint(); }
    {
        // Step 1: execute action `operationSuccessCatcher = moveToPoint();`
        sm->vars.operationSuccessCatcher = moveToPoint();
    } // end of behavior for moveFromEdgeState
    
    // moveFromEdgeState behavior
    // uml: do [!operationSuccessCarcher] TransitionTo(popHistroryAndMoveBackState)
    if (!operationSuccessCarcher)
    {
        // Step 1: Exit states until we reach `traceNeighbourState` state (Least Common Ancestor for transition).
        MOVEFROMEDGESTATE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `popHistroryAndMoveBackState`.
        POPHISTRORYANDMOVEBACKSTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for moveFromEdgeState
    
    // moveFromEdgeState behavior
    // uml: else do TransitionTo(finishTransBetweenTrianglesState)
    {
        // Step 1: Exit states until we reach `traceNeighbourState` state (Least Common Ancestor for transition).
        MOVEFROMEDGESTATE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `finishTransBetweenTrianglesState`.
        FINISHTRANSBETWEENTRIANGLESSTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for moveFromEdgeState
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state MOVETOEDGESTATE
////////////////////////////////////////////////////////////////////////////////

static void MOVETOEDGESTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_MOVETOEDGESTATE;
    
    // moveToEdgeState behavior
    // uml: enter
    {
        // Step 1: execute action ``
    } // end of behavior for moveToEdgeState
}

static void MOVETOEDGESTATE_exit(tracingStateMachine* sm)
{
    // moveToEdgeState behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for moveToEdgeState
    
    sm->state_id = tracingStateMachine_StateId_TRACENEIGHBOURSTATE;
}

static void MOVETOEDGESTATE_do(tracingStateMachine* sm)
{
    // moveToEdgeState behavior
    // uml: do / { setupPose(oldPose);\noperationSuccessCatcher  = moveToPoint(); }
    {
        // Step 1: execute action `setupPose(oldPose);\noperationSuccessCatcher  = moveToPoint();`
        setupPose(sm->vars.oldPose);
        sm->vars.operationSuccessCatcher  = moveToPoint();
    } // end of behavior for moveToEdgeState
    
    // moveToEdgeState behavior
    // uml: do [operationSuccessCatcher] TransitionTo(rotateAroundEdgeState)
    if (sm->vars.operationSuccessCatcher)
    {
        // Step 1: Exit states until we reach `traceNeighbourState` state (Least Common Ancestor for transition).
        MOVETOEDGESTATE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `rotateAroundEdgeState`.
        ROTATEAROUNDEDGESTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for moveToEdgeState
    
    // moveToEdgeState behavior
    // uml: do [iterator > ((int)result.first.size() - 1)] TransitionTo(jumpToBranchState)
    if (sm->vars.iterator > ((int)sm->vars.result.first.size() - 1))
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        exit_up_to_state_handler(sm, tracingStateMachine_StateId_ROOT);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `jumpToBranchState`.
        JUMPTOBRANCHSTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for moveToEdgeState
    
    // moveToEdgeState behavior
    // uml: else do TransitionTo(updValsOnFailState)
    {
        // Step 1: Exit states until we reach `traceNeighbourState` state (Least Common Ancestor for transition).
        MOVETOEDGESTATE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `updValsOnFailState`.
        UPDVALSONFAILSTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for moveToEdgeState
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state POPHISTRORYANDMOVEBACKSTATE
////////////////////////////////////////////////////////////////////////////////

static void POPHISTRORYANDMOVEBACKSTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_POPHISTRORYANDMOVEBACKSTATE;
    
    // popHistroryAndMoveBackState behavior
    // uml: enter
    {
        // Step 1: execute action ``
    } // end of behavior for popHistroryAndMoveBackState
}

static void POPHISTRORYANDMOVEBACKSTATE_exit(tracingStateMachine* sm)
{
    // popHistroryAndMoveBackState behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for popHistroryAndMoveBackState
    
    sm->state_id = tracingStateMachine_StateId_TRACENEIGHBOURSTATE;
}

static void POPHISTRORYANDMOVEBACKSTATE_do(tracingStateMachine* sm)
{
    // popHistroryAndMoveBackState behavior
    // uml: do / { if(!pathHistory.empty() &&\n                    pathHistory.top().typeOfWaypoint == waypointType::EDGE)\n                    {\n                            pathHistory.pop(); \n         }\ntargetPose(previousTriangle);\nmoveToPoint(); }
    {
        // Step 1: execute action `if(!pathHistory.empty() &&\n                    pathHistory.top().typeOfWaypoint == waypointType::EDGE)\n                    {\n                            pathHistory.pop(); \n         }\ntargetPose(previousTriangle);\nmoveToPoint();`
        if(!pathHistory.empty() &&
                            pathHistory.top().typeOfWaypoint == waypointType::EDGE)
                            {
                                    pathHistory.pop(); 
                 }
        targetPose(sm->vars.previousTriangle);
        moveToPoint();
    } // end of behavior for popHistroryAndMoveBackState
    
    // popHistroryAndMoveBackState behavior
    // uml: do TransitionTo(updValsOnFailState)
    {
        // Step 1: Exit states until we reach `traceNeighbourState` state (Least Common Ancestor for transition).
        POPHISTRORYANDMOVEBACKSTATE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `updValsOnFailState`.
        UPDVALSONFAILSTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for popHistroryAndMoveBackState
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state ROTATEAROUNDEDGESTATE
////////////////////////////////////////////////////////////////////////////////

static void ROTATEAROUNDEDGESTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_ROTATEAROUNDEDGESTATE;
    
    // rotateAroundEdgeState behavior
    // uml: enter / { targetPose(previousTriangle);\nedgeTipPose(); }
    {
        // Step 1: execute action `targetPose(previousTriangle);\nedgeTipPose();`
        targetPose(sm->vars.previousTriangle);
        edgeTipPose();
    } // end of behavior for rotateAroundEdgeState
}

static void ROTATEAROUNDEDGESTATE_exit(tracingStateMachine* sm)
{
    // rotateAroundEdgeState behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for rotateAroundEdgeState
    
    sm->state_id = tracingStateMachine_StateId_TRACENEIGHBOURSTATE;
}

static void ROTATEAROUNDEDGESTATE_do(tracingStateMachine* sm)
{
    // rotateAroundEdgeState behavior
    // uml: do / { operationSuccessCatcher = moveToPointWithPenRotation(); }
    {
        // Step 1: execute action `operationSuccessCatcher = moveToPointWithPenRotation();`
        sm->vars.operationSuccessCatcher = moveToPointWithPenRotation();
    } // end of behavior for rotateAroundEdgeState
    
    // rotateAroundEdgeState behavior
    // uml: do [!operationSuccessCatcher] TransitionTo(popHistroryAndMoveBackState)
    if (!sm->vars.operationSuccessCatcher)
    {
        // Step 1: Exit states until we reach `traceNeighbourState` state (Least Common Ancestor for transition).
        ROTATEAROUNDEDGESTATE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `popHistroryAndMoveBackState`.
        POPHISTRORYANDMOVEBACKSTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for rotateAroundEdgeState
    
    // rotateAroundEdgeState behavior
    // uml: else do TransitionTo(moveFromEdgeState)
    {
        // Step 1: Exit states until we reach `traceNeighbourState` state (Least Common Ancestor for transition).
        ROTATEAROUNDEDGESTATE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `moveFromEdgeState`.
        MOVEFROMEDGESTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for rotateAroundEdgeState
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state UPDVALSONFAILSTATE
////////////////////////////////////////////////////////////////////////////////

static void UPDVALSONFAILSTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_UPDVALSONFAILSTATE;
    
    // updValsOnFailState behavior
    // uml: enter / { iterator++;\nneighboutNumber++;\ncurrentTriangle.unreachableCounter++; }
    {
        // Step 1: execute action `iterator++;\nneighboutNumber++;\ncurrentTriangle.unreachableCounter++;`
        sm->vars.iterator++;
        neighboutNumber++;
        sm->vars.currentTriangle.unreachableCounter++;
    } // end of behavior for updValsOnFailState
}

static void UPDVALSONFAILSTATE_exit(tracingStateMachine* sm)
{
    // updValsOnFailState behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for updValsOnFailState
    
    sm->state_id = tracingStateMachine_StateId_TRACENEIGHBOURSTATE;
}

static void UPDVALSONFAILSTATE_do(tracingStateMachine* sm)
{
    // updValsOnFailState behavior
    // uml: do
    {
        // Step 1: execute action ``
    } // end of behavior for updValsOnFailState
    
    // updValsOnFailState behavior
    // uml: do TransitionTo(moveToEdgeState)
    {
        // Step 1: Exit states until we reach `traceNeighbourState` state (Least Common Ancestor for transition).
        UPDVALSONFAILSTATE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `moveToEdgeState`.
        MOVETOEDGESTATE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for updValsOnFailState
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state TRIANGGLEEXTRACTIONSTATE
////////////////////////////////////////////////////////////////////////////////

static void TRIANGGLEEXTRACTIONSTATE_enter(tracingStateMachine* sm)
{
    sm->state_id = tracingStateMachine_StateId_TRIANGGLEEXTRACTIONSTATE;
    
    // trianggleExtractionState behavior
    // uml: enter
    {
        // Step 1: execute action ``
    } // end of behavior for trianggleExtractionState
}

static void TRIANGGLEEXTRACTIONSTATE_exit(tracingStateMachine* sm)
{
    // trianggleExtractionState behavior
    // uml: exit
    {
        // Step 1: execute action ``
    } // end of behavior for trianggleExtractionState
    
    sm->state_id = tracingStateMachine_StateId_ROOT;
}

static void TRIANGGLEEXTRACTIONSTATE_do(tracingStateMachine* sm)
{
    // trianggleExtractionState behavior
    // uml: do / { tringleExtraction(); }
    {
        // Step 1: execute action `tringleExtraction();`
        tringleExtraction();
    } // end of behavior for trianggleExtractionState
    
    // No ancestor handles this event.
}

// Thread safe.
char const * tracingStateMachine_state_id_to_string(tracingStateMachine_StateId id)
{
    switch (id)
    {
        case tracingStateMachine_StateId_ROOT: return "ROOT";
        case tracingStateMachine_StateId_ABORTSTATE: return "ABORTSTATE";
        case tracingStateMachine_StateId_ATTEMPTNEXTCLOSESTSTATE: return "ATTEMPTNEXTCLOSESTSTATE";
        case tracingStateMachine_StateId_EXTRACTPATHSTATE: return "EXTRACTPATHSTATE";
        case tracingStateMachine_StateId_GETBRANCHSTATE: return "GETBRANCHSTATE";
        case tracingStateMachine_StateId_GETDISTANCESTATE: return "GETDISTANCESTATE";
        case tracingStateMachine_StateId_GETORIENTATIONSTATE: return "GETORIENTATIONSTATE";
        case tracingStateMachine_StateId_INITSTATE: return "INITSTATE";
        case tracingStateMachine_StateId_JUMPTOBRANCHPOINTSTATE: return "JUMPTOBRANCHPOINTSTATE";
        case tracingStateMachine_StateId_JUMPTOBRANCHSTATE: return "JUMPTOBRANCHSTATE";
        case tracingStateMachine_StateId_JUMPTOTRIANGSTATE: return "JUMPTOTRIANGSTATE";
        case tracingStateMachine_StateId_LEASTNEIGHBOURSSEARCHSTATE: return "LEASTNEIGHBOURSSEARCHSTATE";
        case tracingStateMachine_StateId_LIFTEDPOSESTATE: return "LIFTEDPOSESTATE";
        case tracingStateMachine_StateId_PLANOMPLSTATE: return "PLANOMPLSTATE";
        case tracingStateMachine_StateId_REACHINGSTATE: return "REACHINGSTATE";
        case tracingStateMachine_StateId_GETCLOSESTSTATE: return "GETCLOSESTSTATE";
        case tracingStateMachine_StateId_GETPOSESTATEINREACHING: return "GETPOSESTATEINREACHING";
        case tracingStateMachine_StateId_MOVESTATEINREACHING: return "MOVESTATEINREACHING";
        case tracingStateMachine_StateId_REACHFAILED: return "REACHFAILED";
        case tracingStateMachine_StateId_REMEMBERPOINTSTATE: return "REMEMBERPOINTSTATE";
        case tracingStateMachine_StateId_STATETOBUILD: return "STATETOBUILD";
        case tracingStateMachine_StateId_TRACENEIGHBOURSTATE: return "TRACENEIGHBOURSTATE";
        case tracingStateMachine_StateId_FINISHTRANSBETWEENTRIANGLESSTATE: return "FINISHTRANSBETWEENTRIANGLESSTATE";
        case tracingStateMachine_StateId_MOVEFROMEDGESTATE: return "MOVEFROMEDGESTATE";
        case tracingStateMachine_StateId_MOVETOEDGESTATE: return "MOVETOEDGESTATE";
        case tracingStateMachine_StateId_POPHISTRORYANDMOVEBACKSTATE: return "POPHISTRORYANDMOVEBACKSTATE";
        case tracingStateMachine_StateId_ROTATEAROUNDEDGESTATE: return "ROTATEAROUNDEDGESTATE";
        case tracingStateMachine_StateId_UPDVALSONFAILSTATE: return "UPDVALSONFAILSTATE";
        case tracingStateMachine_StateId_TRIANGGLEEXTRACTIONSTATE: return "TRIANGGLEEXTRACTIONSTATE";
        default: return "?";
    }
}

// Thread safe.
char const * tracingStateMachine_event_id_to_string(tracingStateMachine_EventId id)
{
    switch (id)
    {
        case tracingStateMachine_EventId_DO: return "DO";
        default: return "?";
    }
}
